[notyet] Add Rawls endpoints for GAWB-3293
broadinstitute/workbench-libs pull request #101
Opened 2018-03-22 20:11 UTC by jmthibault79

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2018-03-22 20:21 UTC, aweng98 reviewed
trait `BillingFixtures.makeRandomId` is `RandomUtil`, right?

2018-03-22 21:27 UTC, jmthibault79 commented
Some klugey API parsing here, to enable only what's necessary for my ticket.

The "right" way for tests to interact with APIs is worth a discussion and will be captured in GAWB-3319.

2018-03-22 22:22 UTC, breilly2 requested changes
Unless there's a really good reason to have it here, I want to see test data closer to the test.

2018-03-22 22:22 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    // dear reader: "workspace namespace" is an archaic term for billing project which is still used in a few places
Then we should start using the preferred term in new code.

2018-03-22 22:22 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +  val SubWorkflowChildMethod = Method(
This stuff is probably needed for a specific test, right? If so, it should be closer to that test. It bothered me a little when `MethodData` was in the firecloud-ui repo but it bothers me a lot now that it is in workbench-libs.

2018-03-23 01:32 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +  val SubWorkflowChildMethod = Method(
I am inclined to agree. If it's used in more than one test, it should be here; if not, it should be with the test.

Offtopic/related/the other side of the same coin: it'd be really nice to have some fixtures that the test environment spins up with (like our user pool).

2018-03-23 14:19 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +  val SubWorkflowChildMethod = Method(
Makes sense.  I'll move it to the test.

2018-03-23 14:40 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    // dear reader: "workspace namespace" is an archaic term for billing project which is still used in a few places
true

2018-03-23 18:52 UTC, breilly2 approved these changes
👍 Thanks for making the change!

2018-03-23 19:14 UTC, aweng98 approved these changes

2018-03-23 19:14 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +      val response = postRequest(url + s"api/workspaces/$billingProject/$workspaceName/submissions", body)
All good, only a short comment on the placement of log. I wish everyone logs action after action took place as the standard practice.

2018-03-23 19:18 UTC, helgridly approved these changes

2018-03-23 19:28 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +      val response = postRequest(url + s"api/workspaces/$billingProject/$workspaceName/submissions", body)
Disagree.  Logging-after means that there's no log when the action fails.

2018-03-23 19:29 UTC, merged