[Leo Issue 215] Reduce time for cluster create request
broadinstitute/workbench-libs pull request #105
Opened 2018-04-04 15:50 UTC by vkumra-broad

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2018-04-04 16:49 UTC, jmthibault79 commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  override def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity], ownerEntity: List[GcsEntity]): Future[GcsBucketName] = {
Move up in file to other `createBucket()`

2018-04-04 16:51 UTC, jmthibault79 commented
Looks good.  Add a note about this in the google CHANGELOG and replace the versions in that file with `TRAVIS-REPLACE-ME`

2018-04-04 17:17 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleStorageDAO.scala
> +  def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity], ownerEntity: List[GcsEntity]): Future[GcsBucketName]
just looking at the signatures: can we replace the 2-param function with default values on the 4-param?

2018-04-04 17:26 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleStorageDAO.scala
> +  def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity], ownerEntity: List[GcsEntity]): Future[GcsBucketName]
+1, can probably write one in terms of the other:
```
def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName): Future[GcsBucketName] = {
  createBucket(billingProject, bucketName, List.empty, List.empty)
```

2018-04-04 17:26 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleStorageDAO.scala
> +  def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity], ownerEntity: List[GcsEntity]): Future[GcsBucketName]
Or even get rid of the other one and write this as:

```
def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity] = List.empty, ownerEntity: List[GcsEntity] = List.empty): Future[GcsBucketName]
```

2018-04-04 17:28 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleStorageDAO.scala
> +  def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, readerEntity: List[GcsEntity], ownerEntity: List[GcsEntity]): Future[GcsBucketName]
Also regarding variable naming, maybe `readerEntity -> readers` and `ownerEntity -> owners` would be more clear.

2018-04-04 17:29 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +import java._
? I suspect this is not used.

2018-04-04 17:31 UTC, rtitle requested changes
Just for removing code duplication of the 2 `createBucket` methods

2018-04-05 15:32 UTC, jmthibault79 commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleStorageDAO.scala
> +  def createBucket(billingProject: GoogleProject, bucketName: GcsBucketName, reader: List[GcsEntity] = List.empty, owner: List[GcsEntity] = List.empty): Future[GcsBucketName]
Pluralize: readers, owners

2018-04-05 17:30 UTC, rtitle approved these changes

2018-04-06 16:18 UTC, merged