Retry token creation on response code 400
broadinstitute/workbench-libs pull request #108
Opened 2018-04-11 17:36 UTC by gpolumbo-broad

Addresses error scene here:  https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/2014/consoleFull

Per @dvoet I have made the change to retry token creation if the response code is 400 or 401.  

**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [x] Bump the version in `project/Settings.scala` `createVersion()`
- [x] Update `CHANGELOG.md` for those libraries
- [x] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-04-11 17:46 UTC, aweng98 commented
```
Optimizing OAuth2 requests
If your app doesn't share credentials across servers, processes, and threads, it may be sending an excessive number of requests to Google. This can cause our servers to enforce rate limits on your app, resulting in performance degradation.
```
An interesting reading from https://developers.google.com/adwords/api/docs/guides/authentication. automation testing definitely falls into this category.

2018-04-11 17:50 UTC, MatthewBemis approved these changes
1 reminder then :+1:

2018-04-11 17:50 UTC, MatthewBemis commented on serviceTest/CHANGELOG.md
> +## 0.9
you'll also want to add a line in this section like ```SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-service-test" % "0.9-TRAVIS-REPLACE-ME"````

(see previous versions)

2018-04-11 18:54 UTC, dvoet commented on project/Settings.scala
> +    version := createVersion("0.9")
I don't think this warrants a version tick, it is backwards compatible

2018-04-11 18:56 UTC, dvoet requested changes
👍 on code but no need to increase the version

2018-04-12 14:37 UTC, dvoet approved these changes

2018-04-12 14:37 UTC, dvoet commented
but still need to do the travis change me thing for the hash

2018-04-18 14:32 UTC, MatthewBemis approved these changes

2018-04-18 19:34 UTC, merged