[Leo Issue 317] Adding GcsEntityType Project
broadinstitute/workbench-libs pull request #110
Opened 2018-04-19 17:30 UTC by kyuksel

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-04-19 17:41 UTC, rtitle commented on README.md
> +Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google" % "0.16-TRAVIS-REPLACE-ME"`
Also set `TRAVIS-REPLACE-ME` in https://github.com/broadinstitute/workbench-libs/blob/develop/google/CHANGELOG.md

2018-04-19 17:53 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +  case object Project extends GcsEntityType { val value = "project" }
I'm wondering if we need to change the model a little more to support project-level ACLs. Currently we have:

```
 case class GcsEntity(email: WorkbenchEmail, entityType: GcsEntityType) {
   override def toString: String = s"${entityType.value}-${email.value}"
 }
```

This works for users and groups, where the target is an email (see https://cloud.google.com/storage/docs/json_api/v1/bucketAccessControls). But for projects the format is: `project-team-projectId`, where `team` is one of (owners, editors, viewers) and projectId is a string. I don't think `GcsEntityType` as it exists right now would support this.

2018-04-19 18:01 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +  case object Project extends GcsEntityType { val value = "project" }
Maybe `GcsEntity` itself should be a trait, so we could have something like this:

```
sealed trait GcsEntity {
  val entityType: GcsEntityType
}
case class EmailGcsEntity(email: WorkbenchEmail, entityType: GcsEntityType) extends GcsEntity {
  override def toString: String = s"${entityType.value}-${email.value}"
}
case class ProjectGcsEntity(team: String, projectNumber: String, entityType: GcsEntityType) extends GcsEntity {
  override def toString: String = s"${entityType.value}-$team-$projectNumber"
} 
```

Just an idea.

2018-04-22 17:30 UTC, kyuksel commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +  case object Project extends GcsEntityType { val value = "project" }
I like your idea. One challenge is `jsonFormat`ing since `{Email,Project}GcsEntity` have different members. In particular for deserialization, we know only at runtime, what the entity type is. This may require an ugly regex on the `entity` string. Let me know if you have a better idea. 

I could also break the `GcsEntity` ADT but then users would need to distinctly specify what entity type they mean to use, which is probably too much inconvenience.

2018-04-23 14:26 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +  case object Project extends GcsEntityType { val value = "project" }
Yeah, I guess the `GcsEntity` deserializer would need to parse the string into the correct `GcsEntity` subclass. There's probably no way around that. One note is I'm not sure these types _need_ JSON serializers since they're for internal use, not exposed over REST APIs. But by convention we've been specifying serializers for all our model classes.

2018-04-24 16:36 UTC, kyuksel commented
From the guidelines on `CONTRIBUTING.md`, it feels like this should be a major version bump since `GcsEntity` is now a trait and the users of it (which is only Leonardo as far as I can tell but still) will need to use one of `EmailGcsEntity` or `ProjectGcsEntity` as implementation. Any thoughts?

2018-04-24 16:39 UTC, kyuksel commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> -  implicit val GcsEntityFormat = jsonFormat2(GcsEntity)
It didn't feel worth creating a custom `RootJsonFormat` extension for `GcsEntity` since it isn't exposed via the APIs or serialized to JSON elsewhere.

2018-04-24 16:44 UTC, kyuksel commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +  case object Project extends GcsEntityType { val value = "project" }
Yea, I realized (unfortunately after starting creating a custom formatter) that the runtime parsing of the `entity` field of the [`BucketAccessControl` resource representation JSON](https://cloud.google.com/storage/docs/json_api/v1/bucketAccessControls) received from Google is irrelevant to this matter and dropped it.

2018-04-25 15:27 UTC, rtitle commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
> +class GcsEntitySpec extends FlatSpecLike with Matchers {
It doesn't seem like this belongs in `GoogleUtilitiesSpec` -- seems like it should be its own class in https://github.com/broadinstitute/workbench-libs/tree/develop/model/src/test/scala/org/broadinstitute/dsde/workbench/model/google

2018-04-25 15:28 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +case class ProjectNumber(value: String) extends AnyVal
Should probably extend `ValueObject` not `AnyVal`

2018-04-25 15:29 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> +    case "owners" => Owners
These `withName` methods should have a default case which throws `WorkbenchException`

2018-04-25 15:30 UTC, rtitle commented on google/CHANGELOG.md
> +SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google" % "0.16-TRAVIS-REPLACE-ME"`
Since we changed `GcsEntity` this probably warrants a version bump from 0.16 to 0.17

2018-04-25 15:32 UTC, rtitle commented on google/CHANGELOG.md
> +SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google" % "0.16-TRAVIS-REPLACE-ME"`
The change is in workbench-model, not google, so update the CHANGELOG and README accordingly.

Also since we're changing GcsEntity it probably warrants a minor version bump (0.10 to 0.11 I think).

2018-04-25 15:32 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/google/GoogleModel.scala
> -  implicit val GcsEntityFormat = jsonFormat2(GcsEntity)
👍

2018-04-25 15:33 UTC, rtitle requested changes
A few minor requests, see above. The `GcsEntity` ADT itself looks good.

2018-04-25 18:26 UTC, rtitle commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
> +import org.broadinstitute.dsde.workbench.model.WorkbenchEmail
Probably unused imports?

2018-04-25 18:27 UTC, rtitle approved these changes
👍 !

2018-04-25 19:50 UTC, merged