misc items
broadinstitute/workbench-libs pull request #116
Opened 2018-05-03 21:44 UTC by aweng98

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-05-03 21:45 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +  val DataSpecMethod = Method(
this method is to be used for DataSpec exclusively.

2018-05-03 21:48 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    options
get rid of selenium warning

2018-05-03 21:50 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserUtil.scala
> +    def condition(condition: => Boolean, timeOutInSeconds: Long = defaultTimeOutInSeconds)(implicit webDriver: WebDriver): Boolean = {
change return type from `Unit` to `Boolean` to extends its' usefulness.

2018-05-03 21:50 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Orchestration.scala
> +        Retry.retry(30.seconds, 20.minutes)({
Free trial project could take more than 10 minutes to create depending on Google service.

2018-05-03 21:55 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +  val DataSpecMethod = Method(
Then it should live in `DataSpec` instead of here

2018-05-03 21:59 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
Why change this?  Before this change, we would clean up a partially-created project which hit a failure partway through.

2018-05-03 22:01 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GroupFixtures.scala
> -    try {
same problem here

2018-05-03 22:29 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
old way doesn't clean up anything because it is outside of try-catch-finally block.

2018-05-04 15:47 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Credentials.scala
> +object Credentials {
a good idea from Rob Title!

reason for change:
1) api calls take bandwidth and time.
2) infrequently causes test to fail when one test is still using a token while other tests request new token for the same test user. Newly issued token turn old token to expire.

2018-05-04 18:38 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
OK.  Why remove the `logger.error()` though?

2018-05-04 19:37 UTC, aweng98 commented
jenkin tests passed
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-PR-fiab-test/1903/

2018-05-04 20:20 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
good catch! I overlooked. It's back in all fixtures now.

2018-05-04 20:22 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Orchestration.scala
> +        Retry.retry(30.seconds, 20.minutes)({
so Retry.retry actually doesn't fail when specified time is up. Anyone notice it too?

2018-05-04 20:24 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    options.addArguments("--no-experiments")
I think this option makes `withSignInReal` works again on local chromedriver.

2018-05-04 20:52 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
No - I mean the logger error in the test code catch block which is no longer present.

2018-05-04 21:13 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      createNewBillingProject(namePrefix, memberEmails)
ah for real it's back.

2018-05-05 00:12 UTC, aweng98 commented
test passed again. one unrelated failure.
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/5480/

2018-05-08 20:08 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Credentials.scala
> +case class Credentials (val email: String, val password: String) extends LazyLogging {
Minor; you don't need to specify `val` in case classes

2018-05-08 20:13 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +            logger.error("", ex)
It seems you lost the error message here

2018-05-08 20:14 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +            fail(ex)
Should this method be throwing `AssertionError`? Seems better to just log-and-rethrow the exception (which is what the previous code was doing).

2018-05-08 20:15 UTC, aweng98 commented
passed https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/5563/

2018-05-08 20:16 UTC, aweng98 commented
passed https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/5564/

2018-05-08 20:21 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GroupFixtures.scala
> +        try {
Again I'm not clear on the need for a nested `try`. It looks like you only clean up groups if the inner try fails, not if the outer one fails. But the outer `try` could have _partially_ succeeded and then failed for 1 email, in which case you'd still want to clean up. Is there harm in having the cleanup in the outermost finally block?

2018-05-08 20:23 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodFixtures.scala
> +        Orchestration.methods.createMethod(method.creationAttributes + ("name" -> methodName))
Again if this succeeds for some elements but 1 of them throws an exception, the successful ones wouldn't get cleaned up.

2018-05-08 20:27 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Orchestration.scala
> +        Retry.retry(30.seconds, 20.minutes)({
I thought it should return the result of the most recent attempt if the time is up.

2018-05-08 20:33 UTC, rtitle requested changes
My main comments are about the change to nested `try`s, which I think could miss cleaning up data in some cases.

2018-05-09 02:04 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Orchestration.scala
> +        Retry.retry(30.seconds, 20.minutes)({
```
def retry[T](interval: FiniteDuration, timeout: FiniteDuration)(op: => Option[T]): Option[T] = {
    val iterations = (timeout / interval).round.toInt
    retry(Seq.fill(iterations)(interval))(op)
  }
```
No. function internally divides duration time by polling interval to get a counter (Integer). retry stops when counter is exhausted, not bound by duration time at all.

2018-05-09 02:07 UTC, aweng98 commented
Undone code change in all fixture files. It was too much of change in one PR.

2018-05-09 16:59 UTC, jmthibault79 approved these changes
Looks good after removing fixture change.  Please add something to the CHANGELOG about Credentials.

2018-05-10 19:43 UTC, rtitle approved these changes
:shipit:

2018-05-10 19:46 UTC, merged