Add (optional) opentelemetry to Google API requests
broadinstitute/workbench-libs pull request #1267
Opened 2023-02-24 19:08 UTC by tlangs

Here's an idea I'm workshopping to add metrics to google api requests. Given the recent incident with the Google Directory API, it might be good to actually have metrics (on our end) of which apps are doing the talking to the api. This would be tested out in Sam first, but any app could theoretically take advantage of it.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2023-02-24 19:42 UTC, dvoet reviewed
You should note that this is technically not capturing metrics on google api requests. It is close but one step removed from reality. It misses retries and any time one of these functions requires more than one google api call e.g. `createGroup` and `listGroupMembers`.

2023-02-24 19:42 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/TelemeterizedHttpGoogleDirectoryDAO.scala
> +                                         implicit val openTelemetry: OpenTelemetryMetrics[IO]
1. you don't need the `implicit` keyword here, the `implicit` at the beginning of the parameter list applies to all parameters in the list
2.  I would just stay away from creating your own implicits, they usually lead to pain
3. could you add `openTelemetry` as an option to `HttpGoogleDirectoryDAO` instead of creating this delegate pattern?

2023-02-24 20:27 UTC, tlangs commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/TelemeterizedHttpGoogleDirectoryDAO.scala
> +                                         implicit val openTelemetry: OpenTelemetryMetrics[IO]
whoops copy-pasta. 

I like the idea of adding it as an option to the `HttpGoogleDirectoryDAO` instead. The fewer classes we have in the inheritance chain, the better.

2023-02-24 22:28 UTC, tlangs commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/TelemeterizedHttpGoogleDirectoryDAO.scala
> +                                         implicit val openTelemetry: OpenTelemetryMetrics[IO]
Updated it so that there's not yet another class

2023-03-01 16:49 UTC, dvoet requested changes
This is still not instrumenting the actual google calls. To do so it needs to count each call to `executeGoogleRequest` which are currently inside retry blocks. So this is missing any retries.

However in looking closer, I see this is [already instrumented](https://github.com/broadinstitute/workbench-libs/blob/develop/google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilities.scala#L214). Maybe you want to see how to hook into those metrics instead?

2023-03-01 16:49 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleDirectoryDAO.scala
> +      openTelemetry.foreach(ot => ot.incrementCounter(s"${metricName}Failure", tags = openTelemetryTags))
`ot.incrementCounter()` produces an `IO` which is never actually executed. You need `unsafeRunSync()` or the like.

2023-03-08 16:56 UTC, tlangs commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleDirectoryDAO.scala
> +      openTelemetry.foreach(ot => ot.incrementCounter(s"${metricName}Failure", tags = openTelemetryTags))
Oh, good catch!

2023-03-08 17:25 UTC, tlangs commented
According to @rtitle, the current instrumentation should "probably be scrapped and redone with more modern opencensus/prometheus tools". 

Apparently, the current stuff is for statsd/HostedGraphite and not pushed to grafana.

2023-03-08 17:31 UTC, rtitle commented
Haven't dug into this PR but yeah, the existing `GoogleCounters` via `workbench-metrics` module (https://github.com/broadinstitute/workbench-libs/blob/develop/google/src/main/scala/org/broadinstitute/dsde/workbench/metrics/GoogleInstrumented.scala) was written long ago for statsd/Hosted Graphite and probably not hooked up to anything anymore. We should re-do metrics with the current tools (OpenCensus, prometheus).

2023-05-23 14:45 UTC, closed without merging