ID-586 signed gs urls
broadinstitute/workbench-libs pull request #1336
Opened 2023-04-27 16:09 UTC by tlangs

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2023-04-27 17:06 UTC, Ghost-in-a-Jar approved these changes

2023-04-27 19:22 UTC, gpolumbo-broad requested changes

2023-04-27 19:22 UTC, gpolumbo-broad commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +                       expirationTimeUnit: TimeUnit = HOURS
Missing a couple params in the scaladoc.  Also - do we want to _require_ an expiration durations?  I think you can also sign URLs that will expire after being accessed a certain number of times for example and I think there are other rules too.  Maybe we'll have other methods for those.  But I'm not sure if we ant `expirationTime: Long` or `expirationTime: Option[Long]`

2023-04-27 19:22 UTC, gpolumbo-broad commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreterSpec.scala
> +  "ioStorage getSignedBlobUrl" should "be able to get a signed blob URL" in ioAssertion {
What about other failure scenarios like if the bucket or blob doesn't exist?  Or if the signing credentials don't work or are invalid some how?

2023-04-28 15:02 UTC, tlangs commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreterSpec.scala
> +  "ioStorage getSignedBlobUrl" should "be able to get a signed blob URL" in ioAssertion {
I don't think we have a way to test that credentials are invalid. The mock here just assumes that credentials are valid, as long as the credential exists. I think we can trust Google that they won't provide access to a URL that the service account doesn't have access to.

2023-04-28 15:57 UTC, tlangs commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +                       expirationTimeUnit: TimeUnit = HOURS
I've replicated what Martha does here as the defaults. I don't think we should change the functionality now, and rather focus on replicating the existing functionality. Certainly something we could revisit, but I don't think its something to do now.

2023-04-28 16:31 UTC, tlangs commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreterSpec.scala
> +  "ioStorage getSignedBlobUrl" should "be able to get a signed blob URL" in ioAssertion {
I just tested the deployed BEE code, and Google will happily sign a URL for a blob that doesn't exist. Once that URL is clicked on, the user gets an error. How much do we want workbench-libs to do?

2023-04-28 17:29 UTC, gpolumbo-broad commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreterSpec.scala
> +  "ioStorage getSignedBlobUrl" should "be able to get a signed blob URL" in ioAssertion {
Great question, I would say to do what Martha does, so it will probably just happily sign a blob that doesn't exist.  I would see if you can write a test asserting this too, if anything just so that if anybody looks at this in the future, they can say, "huh, well, I guess that's the way it's supposed to work because there's a test for it"  You can comment saying we think it's weird and why we left it in.  But these sorts of little decisions are usually worth asserting on and/or commenting.

2023-04-28 17:30 UTC, gpolumbo-broad approved these changes

2023-04-28 19:30 UTC, merged