Added generator function for creating backoff intervals and increased…
broadinstitute/workbench-libs pull request #1399
Opened 2023-06-16 15:50 UTC by sjkobori

… the default backoff interval length

Ticket: https://broadworkbench.atlassian.net/browse/ID-660

Adding longer backoff interval to attempt to not give up on retrying request too soon.

**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [x] Bump the version in `project/Settings.scala` `createVersion()`
- [x] Update `CHANGELOG.md` for those libraries
- [x] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [x] Get two thumbsworth of PR review
- [x] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2023-06-16 19:33 UTC, Shakespeared commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +    if (withJitter) intervals else intervals.map(i => addJitter(i, jitterValue milliseconds))
Is this conditional backwards? Should it be `if (withJitter) intervals.map(i => addJitter(i, jitterValue milliseconds)) else intervals`?

2023-06-20 13:55 UTC, sjkobori commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +    if (withJitter) intervals else intervals.map(i => addJitter(i, jitterValue milliseconds))
yeah, I missed that, good catch 👍

2023-06-20 16:56 UTC, tlangs requested changes

2023-06-20 16:56 UTC, tlangs commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +                                                  jitterValue: Int = 1000
We could combine these two values into a single `jitter: Option[Int]`, where the presence of a value indicates that jitter should happen.

2023-06-20 16:56 UTC, tlangs commented on util/src/test/scala/org/broadinstitute/dsde/workbench/util/RetrySpec.scala
>    "Retry" should "retry 3 times by default" in {
This test name no longer lines up with the functionality of the test.

2023-06-20 16:56 UTC, tlangs commented on util/src/test/scala/org/broadinstitute/dsde/workbench/util/RetrySpec.scala
> +    // log count should be 5 (4 retries plus 1 failure message)
Why did the number of retries change?

2023-06-20 17:06 UTC, sjkobori commented on util/src/test/scala/org/broadinstitute/dsde/workbench/util/RetrySpec.scala
> +    // log count should be 5 (4 retries plus 1 failure message)
Since on line 97 of Retry.scala, we added a new element to allBackoffIntervals which is used for the default amount of retries.

2023-06-20 20:37 UTC, Ghost-in-a-Jar approved these changes

2023-06-22 14:07 UTC, tlangs commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +    }
This can be expressed as 
```scala
jitterValue.flatMap(intervals.map(i => addJitter(i, value milliseconds)).getOrElse(intervals)
```

2023-06-22 14:12 UTC, tlangs commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +    }
Doesn't have to be rewritten this way. @Ghost-in-a-Jar thoughts?

2023-06-22 17:22 UTC, tlangs approved these changes

2023-06-22 17:23 UTC, sjkobori commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/Retry.scala
> +    }
yeah, I think I could go either way. I just figured this one is more legible, but I am happy to switch it if it is preferable.

2023-06-22 17:25 UTC, merged