[GAWB-2146] Instrument Google API calls
broadinstitute/workbench-libs pull request #14
Opened 2017-08-14 17:38 UTC by rtitle

Pulling over common changes from https://github.com/broadinstitute/rawls/pull/748/.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2017-08-14 17:46 UTC, rtitle commented on README.md
> +Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-util" % "0.2-xxxxxxx"`
These were all out of date. Would be cool if there were a way to automate this.

Also: how can I possibly know the latest hash before I merge to dev? :philosoraptor:

2017-08-14 17:57 UTC, rtitle commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
>  class GoogleUtilitiesSpec extends TestKit(ActorSystem("MySpec")) with GoogleUtilities with FlatSpecLike with BeforeAndAfterAll with Matchers with ScalaFutures {
`GoogleUtilitiesSpec` doesn't exist in Rawls? Seems like I could actually add some instrumentation test cases here.

2017-08-14 22:16 UTC, helgridly requested changes
haven't verified that everything's been pulled from rawls correctly but i trust you :) need to update the metrics changelog and make coveralls happy, but otherwise this is a go.

2017-08-14 22:16 UTC, helgridly commented on README.md
> +Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-util" % "0.2-xxxxxxx"`
I agree it would be cool. But not worth dev effort :) Similarly not much we can do about the manual process of updating the readme after merging the PR. Which then bumps the hash of develop anyway. Infinite loop!

2017-08-14 22:16 UTC, helgridly commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
>  class GoogleUtilitiesSpec extends TestKit(ActorSystem("MySpec")) with GoogleUtilities with FlatSpecLike with BeforeAndAfterAll with Matchers with ScalaFutures {
Yeah, I haven't really been backporting.

2017-08-14 22:16 UTC, helgridly commented on google/CHANGELOG.md
> +Instrumentation of Google Cloud HTTP requests.
`InstrumentedRetry` lives in metrics, so you should update that changelog too.

2017-08-14 22:16 UTC, helgridly commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
>  class GoogleUtilitiesSpec extends TestKit(ActorSystem("MySpec")) with GoogleUtilities with FlatSpecLike with BeforeAndAfterAll with Matchers with ScalaFutures {
And I agree. You've dropped below the coverage threshold so you're gonna have to write some tests somewhere :)

2017-08-14 22:17 UTC, rtitle commented on google/CHANGELOG.md
> +Instrumentation of Google Cloud HTTP requests.
Ah right, ok

2017-08-14 22:18 UTC, rtitle commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/GoogleUtilitiesSpec.scala
>  class GoogleUtilitiesSpec extends TestKit(ActorSystem("MySpec")) with GoogleUtilities with FlatSpecLike with BeforeAndAfterAll with Matchers with ScalaFutures {
Yep, working on adding tests :)

2017-08-15 01:32 UTC, rtitle commented
Made changes and got coverage % up!

2017-08-15 14:57 UTC, jmthibault79 approved these changes
woo

2017-08-15 17:24 UTC, merged