Add FailedTestRetryable TestEventReporter
broadinstitute/workbench-libs pull request #150
Opened 2018-07-09 21:54 UTC by aweng98

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-07-09 22:14 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/FailedTestRetryable.scala
> +trait FailedTestRetryable extends TestSuiteMixin with Retries with LazyLogging { this: TestSuite =>
allow any failed test tagged as `Retryable` to rerun when failed.
http://doc.scalatest.org/3.0.1/#org.scalatest.Retries

2018-07-09 22:14 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/TestEventReporter.scala
> +case class TestEventReporter(aggregateReporter: Reporter) extends Reporter with LazyLogging {
capture ScalaTest events to test log

2018-07-09 22:14 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/TestReporterFixture.scala
> +trait TestReporterFixture extends TestSuiteMixin { self: TestSuite =>
allows ScalaTest events write to test log

2018-07-09 23:40 UTC, aweng98 commented
workbench-libs snapshot Jenkins test passed okay
https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Pipeline%20Jobs/job/swatomation-pipeline/7586/

Test events are correctly logged in test log. e.g. `SignInSpec` 
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/4344/artifact/test-reports/TEST-org.broadinstitute.dsde.firecloud.test.user.SignInSpec.log

2018-07-10 17:08 UTC, dvoet commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/FailedTestRetryable.scala
> +          super.withFixture(test) // don't retry if not tagged with `taggedAs(Retryable)` even if test failed
I am not 100% certain how all this fixture stuff works but my read of this code is that the test is running too many times.

line 9 calls `super.withFixture(test)` which runs the test
line 13 calls `withRetryOnFailure(super.withFixture(test))` which does not run the test yet, but it will run it twice if it fails again
line 15 runs the test again

soo, in success case, test is only run once
in failure it will always retry once if isRetryable is false and may retry twice if isRetryable is true.

2018-07-10 17:08 UTC, dvoet requested changes
see comments

2018-07-10 17:33 UTC, dvoet approved these changes

2018-07-10 18:55 UTC, merged