Publisher/Subscriber implementation for Azure Service Bus
broadinstitute/workbench-libs pull request #1646
Opened 2024-01-12 03:23 UTC by giventocode

This PR aims to create Publisher and Subscriber resources for Azure Service Bus that can be used by Scala-based services.

The main features of the implementation are:
- The interfaces/traits of the Azure Service Bus Publisher and Subscriber match the GCP's Pub/Sub implementation. This facilitates the creation of cloud-agnostic abstractions in services. The GCP trait types are not used to keep the implementations independent.
- A message wrapper type called `AzureEvent[A](msg: A, traceId: Option[TraceId], publishedTime: Timestamp)` was introduced.
  - This type has the same properties as the GCP's message type, except for one difference: `PublishedTime` is `java.utils.time.Instant` instead of `com.google.protobuf.TimeStamp`.
  - When the caller sets `TraceId` via the publisher, it is mapped to the `correctationId` of the Service Bus message and is read from the message by the Subscriber.
  - Unit tests for the Subscriber and Publisher that demonstrate functionality. 

Pending Items:
[ ]  Add to the PR manual test that checks the connection and functionality of Service Bus.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2024-01-16 18:48 UTC, cpate4 commented
@giventocode - Out of curiosity, is there a design doc this is associated with to better understand how this will fit in with the rest of the system / architecture? There has been internal discussions about introducing cloud-agnostic code for handling Pub/Sub messages, and I am curious if this fits in with that thought pattern. Thanks!

cc: callisto-team (@LizBaldo, @mlilynolting, @lucymcnatt, @jdcanas, @cindy-broadinstitute)

2024-01-16 20:35 UTC, dvoet commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +trait AzurePublisher[F[_]] {
the is almost identical to `GooglePublisher`. Should we have a single trait that handles both then have interpreters for Azure and Google? Same goes for `AzureSubscriber` and `GoogleSubscriber`.

2024-01-17 14:34 UTC, giventocode commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +trait AzurePublisher[F[_]] {
A single trait would be ideal, but I could not find a practical way to implement it. The project is structured so that each library (google, google2, azure) is independent of each other. This means I would have to either create another library (overkill) or cross-reference google and azure libraries (ugly). Instead of doing that, I created the same signature to maintain the same semantics and facilitate the creation of a single trait with azure and google implementations in the service. This seemed like the least bad option, but I am open to any suggestions.

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureSubscriber.scala
> +//using google protobuf Timestamp for consistency
think the comment is outdated?

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusReceiverClientWrapperInterp.scala
> +  private def handleMessage(context: ServiceBusReceivedMessageContext): Unit =
is this one and `handleError` needed?

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +final case class AzureServiceBusPublisherConfig(topicName: String, connectionString: Option[String])
any reason the connectionString is an `Option`?

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureSubscriberInterp.scala
> +      _ <- logger.error(s"Error in message subscription: ${failure.getMessage}")
`logger.error(failure)(???)`...this way the stacktrace will be logged properly

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureSubscriberInterp.scala
> +import com.google.protobuf.Timestamp
don't think the import is used anymore

2024-01-17 14:36 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +trait AzurePublisher[F[_]] {
it can live in `util2`, both libs depend on it. don't feel strongly either way tho

2024-01-17 14:37 UTC, Qi77Qi commented
oh, I might've some outdated comments that I didn't submit previously...ignore if they're no longer applicable

2024-01-17 18:07 UTC, dvoet commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +trait AzurePublisher[F[_]] {
This seems like the perfect spot to be cloud agnostic.

2024-01-18 14:35 UTC, rtitle commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +trait AzurePublisher[F[_]] {
An approach where the interface is in `util2` and the implementations are in `google2` and `azure` sounds good to me.

2024-01-18 15:08 UTC, rtitle commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisherInterp.scala
> +            .delay(
This maybe should be `Async[F].blocking(..)` instead of `Async[F].delay(..)`. Semantically they're the same, just `blocking` shift the execution on a new cached thread pool.

2024-01-24 13:00 UTC, giventocode commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisher.scala
> +final case class AzureServiceBusPublisherConfig(topicName: String, connectionString: Option[String])
When the connection string is not set, it will use MI.

2024-01-26 13:00 UTC, giventocode commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudPublisher.scala
> +  def publishOne[MessageType: Encoder](message: MessageType, messageAttributes: Option[Map[String, String]] = None)(implicit ev: Ask[F, TraceId]): F[Unit]
I would like to know if using Ask to wrap the TraceId as an implicit value is the best approach. I followed the existing trait (`GooglePublisher`) as a reference, but now I think it might be better to make it an optional parameter with a default value, similar to `messageAttributes`. I would appreciate any feedback.

2024-01-26 13:12 UTC, Qi77Qi commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudPublisher.scala
> +  def publishOne[MessageType: Encoder](message: MessageType, messageAttributes: Option[Map[String, String]] = None)(implicit ev: Ask[F, TraceId]): F[Unit]
I don't feel strongly passing explicitly or implicitly (might be easier to use in `Rawls` if it's explicit)...when the code is used in production, I think we should force caller to pass a `traceId` ideally. But I can see value providing default if you want to provide convenience to caller who doesn't care about being able to link log messages

2024-01-29 21:38 UTC, rtitle commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusReceiverClientWrapper.scala
> +  def createReceiverClientWrapper[F[_], MessageType](
It doesn't seem like the `MessageType` type param is used here?

2024-01-29 21:40 UTC, rtitle commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusReceiverClientWrapperInterp.scala
> +    println(s"Error when receiving message: ${context.getException}.")
I think we should avoid the use of `println` - can we use `slf4j`?

I think you should be able to do something like the following:

1. Add the `StructuredLogger` implicit to `createReceiverClientWrapper`:
```
object AzureServiceBusReceiverClientWrapper {
  def createReceiverClientWrapper[F[_]: StructuredLogger](
    subscriberConfig: AzureServiceBusSubscriberConfig,
    messageHandler: AzureReceivedMessageHandler
  ): AzureServiceBusReceiverClientWrapper =
    new AzureServiceBusReceiverClientWrapperInterp(subscriberConfig, messageHandler)
}
```

2. Add `StructuedLogger` implicit to `AzureServiceBusReceiverClientWrapperInterp`:
```
class AzureServiceBusReceiverClientWrapperInterp[F[_]: StructuredLogger](…)
```

3. "Summon" the implicit at the call site:
```
  private def handleError(context: ServiceBusErrorContext): Unit =
    StructuredLogger[F].error(s"Error when receiving message: ${context.getException.getMessage}")
```

2024-01-29 21:43 UTC, rtitle commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusReceiverClientWrapperInterp.scala
> +    println(s"Error when receiving message: ${context.getException}.")
I think we should avoid the use of println - can we use slf4j?

You could do something like:
```
  private val logger = LoggerFactory.getLogger(classOf[AzureServiceBusReceiverClientWrapperInterp])

… 

  private def handleError(context: ServiceBusErrorContext): Unit =
    logger.error(s"Error when receiving message", context.getException)
```

2024-01-29 21:46 UTC, rtitle commented on google2/CHANGELOG.md
> +## 0.36
Maybe add a `SBT Dependency:` heading under `0.36` to follow the existing pattern.

2024-01-29 21:49 UTC, rtitle approved these changes
Left some minor comments, but overall looks good to me. Thanks for refactoring the Google PubSub stuff to use a common interface

2024-01-29 22:52 UTC, giventocode commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusReceiverClientWrapperInterp.scala
> +    println(s"Error when receiving message: ${context.getException}.")
ahh, yes, thanks, these were temp statements from my manual testing. I'll remove them. Logging (with context) should be covered by the interpreters.

2024-01-30 15:39 UTC, LizBaldo commented
LGTM, I am excited about having a common, cloud agnostic trait for pubsub :)
You might need to make tweaks once you start testing this within leonardo though. If you wanted to, you could leave this PR open, build and publish a snaphot version of the image and use that in your leo PR if you want to save yourself some dev testing cycles

2024-01-30 15:39 UTC, LizBaldo approved these changes

2024-01-30 15:41 UTC, cpate4 requested changes
I definitely liked reading the Azure code (many more comments and descriptions in the code about what and why things were the way they were). 

Biggest questions/comments were:
- does the GCP stuff (at a minimum) need to be a semver breaking change and a major version bump, and
- would it be possible to add the same level of comments that we found in the Azure code paths to the interfaces / traits re: usage, etc?

Thanks!

2024-01-30 15:41 UTC, cpate4 commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudSubscriber.scala
> +)
would it be possible to add comments / documentation for how these traits and case classes are intended to be used?

2024-01-30 15:41 UTC, cpate4 commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudPublisher.scala
> +}
would it be possible to add comments / documentation for how these traits and case classes are intended to be used?

2024-01-30 15:41 UTC, cpate4 commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/AckHandler.scala
> +}
would it be possible to add comments / documentation for how these traits and case classes are intended to be used?

2024-01-30 15:41 UTC, cpate4 commented on project/Settings.scala
>    val openTelemetrySettings = commonSettings ++ List(
general thought questions ...
are the introduction of these interfaces and changes to base classes _possibly_ backwards incompatible changes (thinking through semver)

2024-01-30 15:41 UTC, cpate4 commented on google2/CHANGELOG.md
> +- GoogleSubscriberInterpreter (**Breaking**):
I think this confirms my suspicions in another comment re: this is a breaking change and I believe should be marked as such (e.g. 1.0-TRAVIS-REPLACE-ME) - congratulations!!! 🥳

2024-01-30 15:41 UTC, cpate4 commented on project/Settings.scala
>    val openTelemetrySettings = commonSettings ++ List(
... see comments in `google2/CHANGELOG.md` - it might be that is the only place this backwards incompatible comment applies

2024-01-30 15:41 UTC, cpate4 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +  }
is this code tested elsewhere? is this something we should be validating? (where `#publishOne(...)` is our new way of publishing messages?)

2024-01-30 15:41 UTC, cpate4 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +  }
... it looks like we created a new method with a separate code path and left the original codepath alone. Is it at all possible to push the coerce the two separate code paths? What I am thinking about / concerned with is this code having to support the same set of publish / subscribe. I believe we ideally need them to stay in sync, and the only change (ultimately) should be in the API that we are calling from our clients.

2024-01-30 15:41 UTC, cpate4 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  @deprecated("Use cloudPublisherResource instead", "0.36")
The subscriber looks like it had a harder break - and as such, I am curious if there is any benefit in marking this as deprecated vs just removing it from the code

2024-01-30 15:41 UTC, cpate4 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +  def createAckHandler(consumer: AckReplyConsumer): AckGoogleHandler = new AckGoogleHandler(consumer)
an alternative might be to use `.apply(...)`, and you can use the `.createAckHandler(...)` call at the call-site, but totally up to you

2024-01-30 15:53 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisherInterp.scala
> +                                                messageAttributes: Option[Map[String, String]] = None
maybe do `messageAttributes: Map[String, String] = Map.empty`? Options add more permutation, but I think in this case, we don't need that extra complexity

2024-01-30 15:53 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzureServiceBusSenderClientWrapper.scala
> +trait AzureServiceBusSenderClientWrapper {
shall we tag this one and the implementation class as `private`? I don't think client needs to be aware of this class

2024-01-30 16:11 UTC, cpate4 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +  private def asyncPublishMessage(byteString: ByteString, attributes: Option[Map[String, String]] = None): F[Unit] =
... see @Qi77Qi 's comment above re: empty map vs none - 🙌

2024-01-30 21:13 UTC, giventocode commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +  }
I made minimal changes to the existing GCP implementation to avoid refactoring the tests and to have a quick way to reference the old implementation to facilitate troubleshooting issues as we refactor Leo. Cleaning this up can certainly be a follow-up item.

2024-01-30 21:23 UTC, giventocode commented on project/Settings.scala
>    val openTelemetrySettings = commonSettings ++ List(
For Azure, this is a net new functionality that does not introduce any breaking changes.

2024-01-30 21:42 UTC, cindy-broadinstitute approved these changes
LGTM, it is great to have a cloud agnostic trait for pubsub.

2024-01-30 21:43 UTC, giventocode commented on google2/CHANGELOG.md
> +- GoogleSubscriberInterpreter (**Breaking**):
This library hasn't had any major version upgrades, so I am not sure this change qualifies for that "honor" 😄. I understand and agree with the semver point, but since there is ongoing work in Leo to integrate these changes, and Leo is currently the only client of this library, a minor version update seems reasonable to me.

2024-01-30 21:54 UTC, giventocode commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisherInterp.scala
> +                                                messageAttributes: Option[Map[String, String]] = None
Yeah, I don't like the additional boiler plate required here as well. But this is the resource that made go this way:
https://stackoverflow.com/questions/65256690/best-way-to-model-optional-arguments
I am not a Scala expert, but Option seems to be the "preferred" way.

2024-01-30 22:10 UTC, Qi77Qi commented on azure/src/main/scala/org/broadinstitute/dsde/workbench/azure/AzurePublisherInterp.scala
> +                                                messageAttributes: Option[Map[String, String]] = None
I think it's generally true for optional fields..but in this case, by just doing `messageAttributes: Map[String, String] = Map.empty`, caller can already optionally provide the argument...`Option` isn't adding any value, but rather complicating logic becuz now implementation needs to accomadate for `None`, empty map, which both are the same case

2024-01-31 16:24 UTC, Qi77Qi commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudSubscriber.scala
> +                                    publishedTime: Option[Instant],
any reason why `publishedTime` is optional? in other words, when will it be valid for it to be None?

2024-01-31 17:21 UTC, giventocode commented on util2/src/main/scala/org/broadinstitute/dsde/workbench/util2/messaging/CloudSubscriber.scala
> +                                    publishedTime: Option[Instant],
Good catch. It should not be optional. Initially I thought this was a user-defined property, but later realized is system set and for SB is mapped to the EnqueueTime which should be in all messages. Will fix.

2024-02-02 11:38 UTC, cpate4 approved these changes
Thank you for doing this, @giventocode 
We did talk about the major version bump and NOT doing it.
@rtitle / @dvoet - do we have a documented process for how to do this major version bump so we can follow `semver`?

2024-02-02 12:55 UTC, merged