upgrade cats-core to 1.4.0 in util lib
broadinstitute/workbench-libs pull request #168
Opened 2018-09-30 16:01 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-10-02 15:31 UTC, dvoet requested changes

2018-10-02 15:31 UTC, dvoet commented on project/Settings.scala
> +    version := createVersion("0.4")
I think all modules except model need a version bump because they all depend on util

2018-10-02 15:54 UTC, Qi77Qi commented on project/Settings.scala
> +    version := createVersion("0.4")
errrrrrrrrr

2018-10-19 14:50 UTC, dvoet approved these changes

2018-10-19 18:17 UTC, marctalbott approved these changes

2018-10-19 18:27 UTC, merged