AJ-2020: update swagger-ui, add Content-Security-Policy header
broadinstitute/workbench-libs pull request #1705
Opened 2024-10-02 16:23 UTC by davidangb

This PR is in service to https://broadworkbench.atlassian.net/browse/AJ-2020. That ticket mentions the need for Orch's swagger-ui page to have a `Content-Security-Policy` header. Orch relies on the swagger-ui from workbench-libs, so I'm making changes in workbench-libs.

* updated the version of swagger-ui to latest: 5.17.14
* re-evaluate andd tweaked our customizations to swagger-ui
* evaluated https://broadworkbench.atlassian.net/browse/TOAZ-205 and decided NOT to do that ticket; I think the current approach of checking in a single file containing our customizations is appropriate
* added a `Content-Security-Policy` header, with default value, when serving the swagger-ui html page
* added ability for callers to change the `Content-Security-Policy` headervalue

---

**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [x] Bump the version in `project/Settings.scala` `createVersion()`
- [x] Update `CHANGELOG.md` for those libraries
- [x] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2024-10-02 16:25 UTC, davidangb commented on oauth2/src/main/resources/swagger/index.html
> +  <link rel="stylesheet" type="text/css" href="index.css" />
These changes align our checked-in index.html with the index.html in the 5.17.14 webjar

2024-10-02 16:26 UTC, davidangb commented on oauth2/src/main/resources/swagger/index.html
> -
These classes are in the webjar's index.css and thus don't need to be repeated here

2024-10-02 16:26 UTC, davidangb commented on oauth2/src/main/resources/swagger/index.html
> -
modern swagger-ui supports a `validatorUrl` config value; I'm using that config value below instead of this custom override

2024-10-02 16:28 UTC, davidangb commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +        | pathSuffixTest("index.css") ) {
* The usage of `pathSuffixTest` here for index.css was incorrect, and did not properly serve that file. Updated.
* The `pathSuffixTest("js")` was redundant; all the js we need to serve is already covered by `pathPrefixTest("swagger-ui")`

2024-10-02 16:58 UTC, davidangb commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +        | pathSuffixTest("index.css")) {
* The usage of `pathSuffixTest` here for index.css was incorrect, and did not properly serve that file. Updated.
* The `pathSuffixTest("js")` was redundant; all the js we need to serve is already covered by `pathPrefixTest("swagger-ui")`

2024-10-02 17:38 UTC, LizBaldo approved these changes
I just have one minor comment about a possible cleanup, but otherwise LGTM 👍

2024-10-02 17:38 UTC, LizBaldo commented on oauth2/src/main/resources/swagger/index.html
> +<!-- <script src="./swagger-initializer.js" charset="UTF-8"> </script> -->
Is this something you want to delete or uncomment?

2024-10-02 17:44 UTC, davidangb commented on oauth2/src/main/resources/swagger/index.html
> +<!-- <script src="./swagger-initializer.js" charset="UTF-8"> </script> -->
I've added an extra code comment here to explain - does that help?

2024-10-02 17:45 UTC, LizBaldo commented on oauth2/src/main/resources/swagger/index.html
> +<!-- <script src="./swagger-initializer.js" charset="UTF-8"> </script> -->
Ahh gotcha, yes thank you!

2024-10-02 17:47 UTC, rtitle commented on oauth2/src/main/resources/swagger/index.html
> +  <!-- START Terra customization -->
I guess Terra still has some customizations, so is it not worth doing https://broadworkbench.atlassian.net/browse/TOAZ-205 and reverting to the "stock" `index.html`?

Noting that I do enjoy some of the Terra customizations, like the floating Authorize button when you scroll. (I also haven't tried a modern version of swagger-ui.)

2024-10-02 17:49 UTC, rtitle approved these changes
Didn't test it, but this looks good to me

2024-10-02 17:56 UTC, davidangb commented on oauth2/src/main/resources/swagger/index.html
> +  <!-- START Terra customization -->
Some of the customizations are absolutely necessary, like the call to `initOAuth` and the `oauth2RedirectUrl`. So, we can't use the stock index.html as-is; we need to be able to handle customizations one way or another. I poked at a few approaches:

1. Use the stock index.html, but tweak the akka-http routes such that index.css and swagger-initializer.js are served from workbench-libs instead of the webjar. This just trades committing the HTML file for committing a CSS file plus a JS file; not a win.
2. Use the stock index.html, but tweak the `processSwaggerIndex` function so it does a lot more on-the-fly string replacement to inject our customizations. This would work, but it felt harder for an engineer to understand because the source code for index.html is spread across the webjar plus some Scala string-replace code.
3. Keep the current approach of a checked-in copy of index.html, but add explicit comments to show where our customizations start and stop, hoping to make future swagger-ui updates easier. This is (obv) the approach I took in this PR; it felt simplest and most understandable.

2024-10-02 18:52 UTC, rtitle commented on oauth2/src/main/resources/swagger/index.html
> +  <!-- START Terra customization -->
Ah makes sense - thanks for the explanation

2024-10-03 15:22 UTC, davidangb commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +      "frame-ancestors 'none';"
this adds the appropriate host - https://oauth-proxy.dsp-eng-tools.broadinstitute.org, https://terradevb2c.b2clogin.com, or https://terraprodb2c.b2clogin.com - based on the environment. That way we don't have to list all three hosts in prod.1

question to reviewers: how can we test this will work in prod, without actually releasing it to prod?

2024-10-03 15:28 UTC, LizBaldo approved these changes

2024-10-03 15:28 UTC, LizBaldo commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +      "frame-ancestors 'none';"
Honestly given that this is for swagger only I would feel okay releasing to prod and revert if needed. I do not think we have a lot of non dev swagger users

2024-10-03 15:46 UTC, rtitle commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +  private def cspOpenIdHost: Uri =
The types seem a little off here - it's a `Try(Uri).getOrElse(String)` (which I think derives to `Serializable`).

Maybe this?
```
  private def cspOpenIdHost: String =
    Try(
      Uri
        .parseAbsolute(config.openIdProvider.authorityEndpoint)
        .withPath(Uri.Path.Empty)
        .withQuery(Uri.Query.Empty)
        .toString()
    ).getOrElse("")
```

2024-10-03 15:49 UTC, rtitle commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +      "frame-ancestors 'none';"
Nice, it seems like this will work. For Leo anyway, I think the authority comes from helmfile here: https://github.com/broadinstitute/terra-helmfile/blob/master/values/app/leonardo/live/prod.yaml#L89

I would probably say testing swagger on BEE and dev is probably sufficient - the prod authority should be wired through correctly already.

2024-10-03 15:51 UTC, rtitle reviewed
Looks good overall, 1 comment about Scala types 🤓

2024-10-03 15:51 UTC, rtitle requested changes
Looks good overall, 1 comment about Scala types 🤓

2024-10-03 15:52 UTC, davidangb commented on oauth2/src/main/scala/org/broadinstitute/dsde/workbench/oauth2/OpenIDConnectAkkaHttpOps.scala
> +  private def cspOpenIdHost: Uri =
argg, you are totally right, good catch. Fixed in 6e944da1d76acfa88d4ebb49e2fccc06b8a78aba.

2024-10-03 15:52 UTC, rtitle approved these changes
:shipit:

2024-10-03 15:53 UTC, rtitle approved these changes

2024-10-03 16:00 UTC, merged