add googleFirestore support
broadinstitute/workbench-libs pull request #173
Opened 2018-10-19 21:30 UTC by Qi77Qi

add googlefirestore support
https://broadinstitute.atlassian.net/browse/GAWB-3859

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-10-22 15:05 UTC, helgridly reviewed
I think this is probably fine, but I don't have much context here -- the link to the JIRA says it's about locking in Sam, and I don't see how this solves that problem. Also, I'd find it helpful to see some examples of how to use this code -- I'd usually look to tests for that, but that's hard in library-land.

2018-10-22 15:31 UTC, Qi77Qi commented
@helgridly  The ticket is about adding locking, and we're using firestore as the external db for implementing locking. This PR is just for adding a small utility lib for accessing firestore. There's some example of usage https://github.com/broadinstitute/sam/pull/230/files#diff-807992852986fafb6263c0b0c2bc2d3d...I agree it's probably a good idea to add some example of using this code here too.

For testing, I don't see any exisitng google dao code is actually testing against google, so I thought that's intended.

2018-10-22 15:52 UTC, helgridly commented
Agreed that we don't have a precedent for unit testing googly-DAOs in wb-libs; that was just me griping, not a request :) Thanks for the link to the other PR

2018-10-23 13:11 UTC, dvoet reviewed
How are access credentials passed in? I don't see anything explicit which worries me.

2018-10-23 13:11 UTC, dvoet commented on project/Settings.scala
> +    version := createVersion("0.18"),
this is additive only and is backwards compatible, right? Then we don't need a version bump.
https://github.com/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md#no-version-bump-necessary

2018-10-23 13:11 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleFirestoreOps.scala
> +  def set(collectionName: CollectionName, document: Document, dataMap: Map[String, Any]): F[Instant]
why does this return an Instant?

2018-10-23 13:46 UTC, Qi77Qi commented
@dvoet , from google's doc, creds are set by `export GOOGLE_APPLICATION_CREDENTIALS=pathToCredJson`

2018-10-23 13:46 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleFirestoreOps.scala
> +  def set(collectionName: CollectionName, document: Document, dataMap: Map[String, Any]): F[Instant]
it's the `Instant` when the record is being updated

2018-10-23 14:04 UTC, dvoet commented
I don't think we set that... we use different credentials for different things so need tighter control. We need to figure out how to pass in credentials programmatically like we do for our other google access daos.

2018-10-25 14:25 UTC, dvoet requested changes

2018-10-25 14:25 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleFirestoreOpsInterpreters.scala
> +  def firestore(credential: InputStream): Resource[IO, Firestore] = Resource.make[IO, Firestore](IO(FirestoreOptions
Instead of an InputStream take a GoogleCredentialMode (see the other google DAOs)

2018-11-14 18:06 UTC, Qi77Qi commented
it should be safe to bump grpc since sam service test runs just fine

2018-11-14 19:48 UTC, dvoet requested changes

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +      status <- Option(nullableDocumentSnapshot).fold[F[LockStatus]](af.pure(Available)) { documentSnapshot =>
prefer case statement to fold

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +          sf.raiseError(new WorkbenchException(s"can't get lock: ${e}"))
`s"timeout waiting for lock: ${e}"`

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  }(_ => releaseLock(lock))
does this release the lock even if it was not acquired (e.g. timeout waiting for lock)?

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  private[dsde] val EXPIRESIN = "expiresIn"
since this is an absolute time call it expiresAt, expiresIn indicates an interval (e.g. expires in 30 seconds as opposed to expires at 3:30PM)

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  private[dsde] def setLock[F[_]](tx: Transaction, documentReference: DocumentReference, expiresIn: FiniteDuration)(implicit sf: Sync[F], timer: Timer[F]): F[Unit] =
why are setLock and retry in the companion object? I think we should keep them in the same place as the other functions.

2018-11-14 19:48 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  def withLock(lock: LockPath)(implicit af: Async[F]): Resource[F, Unit] = Resource.make{
Sometimes we use a Sync and sometimes Async... can we fix on one? These implicits are also named af and sf which have not meaning to me. Is there a reason they are passed in to each function individually instead of at the instance level like the execution context and timer?

2018-11-14 20:39 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  def withLock(lock: LockPath)(implicit af: Async[F]): Resource[F, Unit] = Resource.make{
`Async` extends from `Sync`, see https://typelevel.org/cats-effect/typeclasses/. So the difference being I can use `setLock` with some data type that doesn't have `Async` instance (say `State`), vs `withLock` can only be used with data type that has `Async` instance, which can be handy in testing. It's true in app code, we'll probably always use `IO` or some other things, so there's not much difference there.

2018-11-14 20:45 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  private[dsde] def setLock[F[_]](tx: Transaction, documentReference: DocumentReference, expiresIn: FiniteDuration)(implicit sf: Sync[F], timer: Timer[F]): F[Unit] =
For `setLock`, I don't expect user to call `setLock` directly on a `DistributedLock` instance. Yet being in companion object is handy for testing and from console. But I don't mind putting it in `DistribtuedLock` if you feel strongly about it.

For `retry`, it doesn't have much to do with `DistributedLock`. We probably should move it somewhere else if it's worth it. But there're other libraries provides similar functionality. So I think for now, companion object seems the best place for it.

2018-11-14 21:05 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  }(_ => releaseLock(lock))
I don't think it would. The signature for second parameter is `release: A => F[Unit]`, which means there has to be an `A`.

Also
```
Resource.make(IO.raiseError[Int](new Exception))(a => IO(println(a)))
res4: Resource[IO, Int] = Allocate(Map(RaiseError(java.lang.Exception), scala.Function1$$Lambda$35/1529306539@a18649a, 1))

qi-automation@ res4.use(x => IO.unit).unsafeRunSync()
java.lang.Exception
  ammonite.$sess.cmd4$.<init>(cmd4.sc:1)
  ammonite.$sess.cmd4$.<clinit>(cmd4.sc)

```

2018-11-15 01:51 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  private[dsde] def setLock[F[_]](tx: Transaction, documentReference: DocumentReference, expiresIn: FiniteDuration)(implicit sf: Sync[F], timer: Timer[F]): F[Unit] =
maybe look at org.broadinstitute.dsde.workbench.util.Retry

As for setLock I think we should move it. I am trying to get to consistency. The more inconsistencies, the more chance for misunderstandings, the more questions of why this or that, the more general confusion looking at the code.

2018-11-15 02:28 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/util/DistributedLock.scala
> +  def withLock(lock: LockPath)(implicit af: Async[F]): Resource[F, Unit] = Resource.make{
I understand all that. But back to consistency. There is no real reason to use Sync. I understand that it is all that is needed for setLock. In some other context it would probably be fine. But it is strictly internal. Making it different raises the question of why which makes it harder to comprehend.

Also I would say just make it implicit at the class level instead of on each function.

2018-11-15 18:51 UTC, dvoet approved these changes

2018-11-15 18:57 UTC, merged