policy sync endpoints for sam automation tests
broadinstitute/workbench-libs pull request #181
Opened 2018-11-02 19:08 UTC by marctalbott

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2018-11-02 19:13 UTC, helgridly commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/SamModel.scala
> +final case class AccessPolicyMembership(memberEmails: Set[String], actions: Set[String], roles: Set[String])
aww really?

2018-11-02 19:14 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Sam.scala
> +    def addUserToManagedGroupPolicy(groupName: String, policyName: String, memberEmail: String)(implicit token: AuthToken): Unit = {
if you want to rename these functions, go ahead, but leave the old ones there + mark them as deprecated + make them call the new ones

2018-11-02 19:14 UTC, helgridly requested changes
i think there are a couple minor things you can do to make this an entirely nonbreaking change

2018-11-02 19:56 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Sam.scala
> +    def addUserToManagedGroupPolicy(groupName: String, policyName: String, memberEmail: String)(implicit token: AuthToken): Unit = {
if we know this function is not used by any code other than sam, I'd rather just rename them to reduce maintenance overhead.

2018-11-06 16:22 UTC, dvoet approved these changes

2018-11-06 16:36 UTC, Qi77Qi commented on model/CHANGELOG.md
> +- Remove duplicated `SamModel`
I think you'll need to bump all other modules that depend on `model`, which is all modules I think.

2018-11-06 16:46 UTC, helgridly commented on model/CHANGELOG.md
> +- Remove duplicated `SamModel`
yes (sadly)

2018-11-06 18:39 UTC, marctalbott commented on model/CHANGELOG.md
> +- Remove duplicated `SamModel`
Just to be clear, you mean that all the other libs need minor version bumps as well, is that correct?

2018-11-06 18:50 UTC, helgridly commented on model/CHANGELOG.md
> +- Remove duplicated `SamModel`
yes

2018-11-06 20:38 UTC, helgridly approved these changes

2018-11-06 20:43 UTC, merged