Queue
broadinstitute/workbench-libs pull request #201
Opened 2019-01-17 21:59 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-01-18 20:15 UTC, dvoet requested changes

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +      val byteString = ByteString.copyFromUtf8(a.asJson.toString()) //This will turn a case class into raw json string
I would use `noSpaces` instead of `toString`

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def publish[A: Encoder]: Sink[F, A]
should we also have a function that just takes a `String`? Maybe someone does not want a json message.

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def publish[A: Encoder]: Sink[F, A]
we should also have a function that can publish more than one message at a time. Watch out for limits (https://cloud.google.com/pubsub/quotas):
per publish request
10MB (total size)
1,000 messages

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +private[google2] class GooglePublisherInterpreter[F[_]: Async: Timer: ContextShift](
do you need Timer and ContextShift?

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +            publisher.publish(message),
we need retries

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +    } yield pub
I find all the boilerplate with Sync and Resource makes the code difficult to read. All the pertinent details are hidden. Would extracting each part of the for comp into a function help?

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +final case class SubsriberConfig(projectTopicName: ProjectTopicName, achDeadLine: FiniteDuration)
spelling: Subs c riberConfig and ac k DeadLine

2019-01-18 20:15 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            .setCredentialsProvider(FixedCredentialsProvider.create(credential))
There are some other settings that looks like we expose, e.g. the flow control settings

2019-01-26 02:06 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def publish[A: Encoder]: Sink[F, A]
I can add `pubString`. I don't think google's publisher client expose a `publishN` function.

2019-01-26 02:07 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +private[google2] class GooglePublisherInterpreter[F[_]: Async: Timer: ContextShift](
no, I don't...nice catch 👍

2019-01-26 02:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +    } yield pub
I kinda prefer to have them all together here so that I don't need to jump around to see what initialization and shutdown look like for each resource. But maybe I'm not seeing what you have in mind. Let me know if you have some examples.

2019-01-26 02:33 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            .setCredentialsProvider(FixedCredentialsProvider.create(credential))
since fs2 is pull based, so I don't think we need flow control settings?

2019-01-26 02:40 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +          case _: com.google.api.gax.rpc.AlreadyExistsException => ()
it's interesting that emulator and real pubsub didn't throw the same exception type...
from real pubsub it looks like
```
[info]   com.google.api.gax.rpc.AlreadyExistsException: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Resource already exists in the project (resource=qi-pubsub-test).
```

2019-01-29 14:18 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            .setCredentialsProvider(FixedCredentialsProvider.create(credential))
I think we do. My read of https://cloud.google.com/pubsub/docs/pull makes me think that the client library will suck as many messages as it can onto the client for local processing. The default limit seems to be 10k messages or 10MB. I don't really see a reason for numbers as large as that.

2019-01-29 14:38 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +        cb =>
can we call this callback instead of cb or something more descriptive?

2019-01-29 15:02 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +        cb =>
it's quite typical to call this `cb` when using `async`..also calling it callback makes it easy to confuse with google's [callback](https://github.com/broadinstitute/workbench-libs/pull/201/files#diff-19849200e5d5dfcd69380863c18d949bR15) argument

2019-02-05 18:16 UTC, dvoet approved these changes

2019-02-05 21:04 UTC, marctalbott commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def publish[MessageType: Encoder]: Sink[F, MessageType]
I'm not sure I understand this syntax, are these both implicits? Or is `MessageType` a kind of `Encoder`?

2019-02-05 21:04 UTC, marctalbott commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def resource[F[_]: Async: Timer: ContextShift, MessageType: Encoder](config: PublisherConfig): Resource[F, GooglePublisher[F]] = for {
Same question here, from what I understand this means `F[_]` implements (or has these traits) `Async`, `Timer`, `ContextShift`, but how does that then relate to `MessageType` and `Encoder`?

2019-02-05 21:04 UTC, marctalbott commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +    val subscription = ProjectSubscriptionName.of(subsriberConfig.projectTopicName.getProject, subsriberConfig.projectTopicName.getTopic)
spelling: subscriberConfig

2019-02-05 21:04 UTC, marctalbott commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +    callback =>
Where does this `callback` come from?

2019-02-05 21:04 UTC, marctalbott commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GooglePubSubSpec.scala
> +        .build()))(p => /*IO(p.shutdown()) >>*/ IO.unit) //TODO: shutdown properly. Somehow this hangs the publisher unit test
Are there tickets for these TODOs already?

2019-02-05 21:04 UTC, marctalbott commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GooglePubSubSpec.scala
> +                  IO(event.consumer.ack()).void >> terminateSubscriber.set(true)
From what I can tell, the `>>` is an alias for `flatMap`? Could we just use `flatMap` here for readability's sake or is `>>` a sufficiently common alias that I should just get used to looking at it?

2019-02-06 15:17 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def resource[F[_]: Async: Timer: ContextShift, MessageType: Encoder](config: PublisherConfig): Resource[F, GooglePublisher[F]] = for {
in `resource[F[_]: Async: Timer: ContextShift, MessageType: Encoder]` the `:` means something other inheritance. The way to know is that they are in the parameterized type list. In this case it means that there must be a companion implicit object. E.g. for `MessageType` there must be an implicit object in scope of type `Encoder[MessageType]`. For `F[_]` there must be `Async[F[_]]`, `Timer[F[_]]` and `ContextShift[F[_]]`.

2019-02-06 15:18 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def resource[F[_]: Async: Timer: ContextShift, MessageType: Encoder](config: PublisherConfig): Resource[F, GooglePublisher[F]] = for {
https://docs.scala-lang.org/tutorials/FAQ/context-bounds.html

2019-02-13 12:13 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +    in.flatMap {
when I see `A`, I know right away that it can be any type...but if I see `MessageType`, I have to look closer to make sure if it's not some type alias defined else where.

But if `MessageType` makes it more intuitive for other people, I'm fine with it

2019-02-13 12:18 UTC, Qi77Qi commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GooglePubSubSpec.scala
> +        .build()))(p => /*IO(p.shutdown()) >>*/ IO.unit) //TODO: shutdown properly. Somehow this hangs the publisher unit test
@marctalbott  These TODOs probably don't worth tickets. It'll probably need quite some time to figure out why the publisher hangs, which might turn out some bug in emulator publisher's shutdown code. But it really doesn't affect us that much.

2019-02-13 12:21 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +    callback =>
this `callback` is used to terminate this `F`. When `callback` is called with either a left value or a right value, `F` will be terminated with either an exception or a successful value.

2019-02-13 12:24 UTC, Qi77Qi commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/GooglePubSubSpec.scala
> +                  IO(event.consumer.ack()).void >> terminateSubscriber.set(true)
`io1 >> io2` is indeed just alias for `io1.flatMap(_ => io2)`...but it's probably the most common syntax when using fs2 or some other FP libraries (it's widely used in fs2 source code too). So I think it's worth getting some familiarity.

2019-02-14 13:03 UTC, marctalbott approved these changes

2019-02-14 13:04 UTC, merged