Add KMS interpreter and service
broadinstitute/workbench-libs pull request #202
Opened 2019-01-28 23:25 UTC by marctalbott

This is still a wip as it may change depending on the automation test I'm currently working on for Sam, but this is what I've got so far

**PR checklist**
- [x] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [x] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [x] Get two thumbsworth of PR review
- [x] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-01-29 02:03 UTC, Qi77Qi commented
👍  overall looks really good

2019-01-29 02:03 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleKmsInterpreter.scala
> +  override def createKeyRing(project: String, location: String, keyRingId: String): F[KeyRing] = {
there's a `GoogleProject` type I think.
I'll make custom type for `location` and `keyRingId`. Stringy types are too error prone

Same comment goes for other methods

2019-01-29 02:03 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleKmsInterpreter.scala
> +      otherBindings = currentIamPolicyOpt.get.getBindingsList.asScala.toList.filter(binding => !binding.getRole.equals(role))
calling `.get` on `Option` will throw exception. It should be avoided in general. I think for this case, you can use `map` to get inside the `Option`, and at the end do `.getOrElse(List.empty)`

Something like `currentIamPolicyOpt.map(x => x.getBindingsList.asScala.toList.filter(binding => !binding.getRole.equals(role)).getOrElse(List.empty)`

This way you don't need to worry about exceptions.


Also, double check the equality check works the way you expect

2019-01-29 02:03 UTC, Qi77Qi commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleKmsInterpreter.scala
> +      newBindings = currentIamPolicyOpt.get.getBindingsList.asScala.toList.filter(binding => binding.getRole.equals(role)).map { binding =>
same comment. Don't use `.get` on `Option`, it defeats the purpose of using `Option` in the first place.

2019-01-29 02:03 UTC, Qi77Qi commented on google/src/test/scala/org/broadinstitute/dsde/workbench/google/mock/MockGoogleKmsInterpreter.scala
> +object MockGoogleKmsInterpreter extends GoogleKmsService[IO] {
minor, I kinda prefer `Fakexxx`. It's the same naming as some emulators, and it's easy to know that it's new google code as opposed to older google module.

2019-01-31 20:17 UTC, dvoet requested changes
1 little thing

2019-01-31 20:17 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleKmsInterpreter.scala
> +      newPolicy = Policy.newBuilder(currentIamPolicyOpt.get)
.get is bad practice... how can you handle None?

2019-02-05 16:23 UTC, dvoet approved these changes

2019-02-21 03:45 UTC, Qi77Qi approved these changes
thought I approved it a while back..Maybe the approval is gone since you rebased?

2019-02-21 03:46 UTC, Qi77Qi commented
nvm..I was thinking of another PR

2019-03-05 15:22 UTC, merged