add notification creater and topic creater
broadinstitute/workbench-libs pull request #205
Opened 2019-02-28 05:24 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-02-28 09:44 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +import fs2.Pipe
newer version of fs2 deprecated `Sink` because they want to reduce type aliases.

2019-03-01 01:44 UTC, dvoet requested changes
a couple minor comments but in general all calls to google need retries and we need to log all calls to google.

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +final case class MetadataNotificationCreaterConfig(pathToCredentialJson: String, googleUrl: Uri)
Metadata does not belong in the name of this class

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +        ).withEntity(notificationBody))
need retries and logging for google calls

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameEncoder: Encoder[ProjectTopicName] = Encoder.encodeString.contramap(
what is contramap? I looked it up and did not find much understandable.

`Generally speaking, if you have some context F[A] for type A, and you can get an A value out of a B value — Contravariant allows you to get the F[B] context for B.`

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val notificationEventTypesEncode: Encoder[NotificationEventTypes] = Encoder.encodeString.contramap(eventType => eventType.asString)
missing `r` at end of notificationEventTypesEncode

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameDecoder: Decoder[ProjectTopicName] = Decoder.decodeString.emap { s =>
why do we need to parse this? I feel like we will just get ourselves into trouble when google decides to change it. Why don't we treat the topic name as an opaque string?

2019-03-01 01:44 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdmin.scala
> +  def fromCredentialPath[F[_]: Logger: Sync](pathToCredential: String): Resource[F, GoogleTopicAdmin[F]] = for {
are Logger or Sync required, same question below

2019-03-01 02:56 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameEncoder: Encoder[ProjectTopicName] = Encoder.encodeString.contramap(
When I first encounter `contramap`, I found it hard to understand abstractly too. In this example, what I'm doing is, derive a `Encoder[ProjectTopicName]` from the built-in `Encoder[String]`. In order to do that, `circe` provides `contramap` combinator, which does exactly that as long as I tell it "how to convert `ProjectTopicName` to `String`".

 You can think of `contramap` as the reverse of `map`. For instance, on the decoder side, I could have done `Decoder.decodeString.map(s => some function convert s to ProjectTopicName)` to get a `Decoder[ProjectTopicName]` (I didn't use simple `map` because I want to handle failures when converting from string to `ProjectTopicName`).

It's probably hard to remember `contramap` is for `Encoder`, `map` is for `Decoder`, so what I normally do is knowing I need to derive some `Encoder[A]`, `Decoder[A]` from built-in ones, just try typing either `map`,  `contramap` and see which one comes up

2019-03-01 02:56 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameDecoder: Decoder[ProjectTopicName] = Decoder.decodeString.emap { s =>
we need to parse this because we need to check if this matches the topic user wants to create. If we don't parse it, then we are expecting user to input a String like `//pubsub.googleapis.com/projects/{project-identifier}/topics/{my-topic}` as `topic`, which is very error prone

2019-03-01 02:56 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdmin.scala
> +  def fromCredentialPath[F[_]: Logger: Sync](pathToCredential: String): Resource[F, GoogleTopicAdmin[F]] = for {
`Logger` is required because of https://github.com/broadinstitute/workbench-libs/pull/205/files#diff-0e40702893382d56e7c9ae448bc0c692R17.  But I don't mind removing this log line if you don't want it

2019-03-01 04:53 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreater.scala
> +  def apply[F[_]: Concurrent: Timer](httpClient: Client[F], config: MetadataNotificationCreaterConfig): GoogleStorageNotificationCreater[F] =
I'd like to keep this constructor because the input `httpClient` could already have retry and logging enabled

2019-03-01 04:53 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +        ).withEntity(notificationBody))
addressed in https://github.com/broadinstitute/workbench-libs/pull/205/files#diff-9ccb856d00f16de514c16be293b328f7R17

2019-03-01 06:19 UTC, Qi77Qi commented on util/src/main/scala/org/broadinstitute/dsde/workbench/util/ExecutionContexts.scala
> -import cats.implicits._
this is no longer needed because later version of cats-effect added `map` directly on `Resource` instead of relying on syntax extension

2019-03-01 15:32 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameEncoder: Encoder[ProjectTopicName] = Encoder.encodeString.contramap(
I think I get it now, but this is the kind of thing that makes code hard to understand. The doc for this function is `Create a new Encoder by applying a function to a value of type B before encoding as an A.` The abstract types make it hard to understand and the type A is out of context so it takes a bunch of squinting to figure it out.

Unless I know a bunch of stuff already it is hard to understand what the code is doing. And the first level of documentation I can find is not very helpful as it is far too abstract.

2019-03-01 15:33 UTC, dvoet commented
also a spelling mistake throughout creator, not creater

2019-03-01 16:04 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreater.scala
> +  def withRetryAndLogging[F[_]: Concurrent: Timer](httpClient: Client[F], config: NotificationCreaterConfig, retryPolicy: RetryPolicy[F]): GoogleStorageNotificationCreater[F] = {
so if I under this right, it is up to the calling code to use this. I think it would be better if the calling code does not have to deal with retries (what do they know about how to retry). The same goes for logging. I agree that the calling program should be able to modify logging but it should be via config, not code.

2019-03-01 16:04 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameEncoder: Encoder[ProjectTopicName] = Encoder.encodeString.contramap(
The good thing is once you pick it up, it's applicable to many things :P. Here is more doc about the general idea https://typelevel.org/cats/typeclasses/contravariant.html

2019-03-01 16:09 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameDecoder: Decoder[ProjectTopicName] = Decoder.decodeString.emap { s =>
what I am getting at is that we should represent `ProjectTopicName` as a string not its constituent parts. We can have a constructor of `ProjectTopicName` that takes project and topic and forms the right string if we want.

Anyway, I have been burned by stuff like this changing and I have found it better to treat these names as opaque strings.

2019-03-01 16:12 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +      _ <- Sync[F].delay(topicAdminClient.setIamPolicy(topicName, updatedPolicy))
how does logging work here?

2019-03-01 16:29 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameEncoder: Encoder[ProjectTopicName] = Encoder.encodeString.contramap(
I am trying to poke at the common sentiment I have been hearing that our code is really hard to ramp up on. The more times we say "once you pick it up" the harder the overall code is to understand for outsiders.

2019-03-02 00:21 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreaterInterpreter.scala
> +  implicit val projectTopicNameDecoder: Decoder[ProjectTopicName] = Decoder.decodeString.emap { s =>
@dvoet `ProjectTopicName` is a google lib type. It's what google expects if we're using google library. It'd quite inconvenient if caller needs 2 representations of "topic" in order to create the notification, and create the topic. Also, what `String` representation you're envisioning?

2019-03-02 00:25 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +      _ <- Sync[F].delay(topicAdminClient.setIamPolicy(topicName, updatedPolicy))
I just added a log line https://github.com/broadinstitute/workbench-libs/pull/205/files/9826a9b00014ded05d8fba131327a89dd687ec78#diff-0e40702893382d56e7c9ae448bc0c692R35

2019-03-04 21:09 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreater.scala
> +  def withRetryAndLogging[F[_]: Concurrent: Timer](httpClient: Client[F], config: NotificationCreaterConfig): GoogleStorageNotificationCreater[F] = {
I think this one should be the default constructor (call it apply) and the current apply function should be `withoutRetryAndLogging` if we event want it at all

2019-03-04 21:29 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +      _ <- Sync[F].delay(topicAdminClient.setIamPolicy(topicName, updatedPolicy))
We need to have a standardized log statement for every individual google call we make in all the places we make google calls in this new google2 lib. Look at what the older google lib does. I understand that this library is different so the mechanism will be different, even the format can be different. I just want the information in our logs so that when we have google problems we can be precise about what we were doing. We need to log the api call, the parameters and any error response. Elapsed time is a nice to have (what we currently have is not particularly accurate).

I know this is not necessarily specific to this PR but I have been saying this for a while. This PR can't merge until we have the solution. Then we need to make sure that the other google2 interpreters have it too.

2019-03-05 06:06 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +      _ <- Sync[F].delay(topicAdminClient.setIamPolicy(topicName, updatedPolicy))
I added some logging https://github.com/broadinstitute/workbench-libs/pull/205/files#diff-19849200e5d5dfcd69380863c18d949bR31...
1. Things like parameters are is basically logged specifically at call site such as https://github.com/broadinstitute/workbench-libs/pull/205/files#diff-ba19528522770daf7afddd8a9a256c8bR94

2. I added an optional `traceId` field. The idea is we can search for this `traceId` in kibana and see all logs for a given `traceId`.

2019-03-05 15:38 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +  def retryGoogleF[F[_]: Timer: RaiseThrowable: Logger, A](retryConfig: RetryConfig)(fa: F[A], traceId: Option[TraceId], action: String): Stream[F, A] =
This needs to log per attempt, not once for all attempts. Capturing overall elapsed time is useful but the intent is to capture each call individually.

2019-03-05 18:40 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/LoggerSyntax.scala
> +final case class LoggerSyntax[F[_]](log: Logger[F]) extends AnyVal {
docs as to what this class does, what is `ctx` in all the val and def names below? Don't abbreviate message with msg.

2019-03-05 18:50 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      s"creating bucket $billingProject/$bucketName with acls $acl"
I would like to see something that mirrors the exact api call a little better, e.g.
`s"com.google.cloud.storage.Storage.create($bucketInfo, ${BucketTargetOption.userProject(billingProject.value)})`

2019-03-05 19:52 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreatorInterpreter.scala
> +  implicit val projectTopicNameDecoder: Decoder[ProjectTopicName] = Decoder.decodeString.emap { s =>
use `ProjectTopicName.parse` instead of writing our own parsing code.

2019-03-05 19:56 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +  def listObjectsWithPrefix(bucketName: GcsBucketName, objectNamePrefix: String, maxPageSize: Long = 1000, traceId: Option[TraceId] = None): Stream[F, GcsObjectName]
doc what traceId is for

2019-03-06 08:43 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/LoggerSyntax.scala
> +final case class LoggerSyntax[F[_]](log: Logger[F]) extends AnyVal {
it means logging with some context `A`, which can be anything as long as there's an `Encoder[A]` in scope.

For instance, `Logger[F].ctxError[LoggableGoogleCall]("Failed", e).run(loggableGoogleCall)` and `Logger[F].ctxInfo[LoggableGoogleCall]("Succeeded").run(loggableGoogleCall)` will log `loggableGoogleCall` in the same way given same `Encoder[LoggableGoogleCall]`.

This can be useful in application logging as well. Say we have `val context = SamAPIContext(traceId: TraceId, userAgent: UserAgent)`, for a given api request we can do things like  `Logger[F].ctxDebug[SamAPIContext]("request initiated").run(context)`, `Logger[F].ctxError[SamAPIContext]("user not found", e).run(context)`, , and they will have the context logged in the same format.

2019-03-06 11:40 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/LoggerSyntax.scala
> +final case class LoggerSyntax[F[_]](log: Logger[F]) extends AnyVal {
https://typelevel.org/cats/datatypes/kleisli.html if you're not familiar with `Kleisli`...if you're familiar with reader monad (Anu mentioned you guys were either using it or she's used it. I can't remember exactly), it's similar to `Kleisli`

2019-03-06 15:39 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/LoggerSyntax.scala
> +final case class LoggerSyntax[F[_]](log: Logger[F]) extends AnyVal {
The terms `context` and `syntax` as they are used here don't fit in how I usually think of them (or at least I don't see it yet). Can we name things in terms of what they do instead of what they are?

But looking at it a little more, I am having trouble seeing the benefits of having this class. It seems to do 2 things, serialize json and insert a message into the json. This is only used in the google retry code and some special case logic creating topics.

I think the special case for creating topics (topic already exists) should stop being a special case and the retry config should be used instead so that an `AlreadyExistsException` is not retried.

I think the message (which could just be a `success` boolean) should be part of the LoggableGoogleCall and encode json at the call site. Also check if the logger is enabled at the call site.

2019-03-07 14:03 UTC, dvoet approved these changes

2019-03-08 13:47 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +          Logger[F].error(e)(loggableGoogleCall.asJson.noSpaces) //google library logs error response as well. Revisit if this is too noise
Log this at info level too. If the failure is successfully retried then this wasn't an error. If it ends up getting propagated then it is up to the caller to decide if it is an error (e.g. the AlreadyExistsException is not an error when creating a topic)

2019-03-10 19:06 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +class GoogleTopicAdminInterpreter[F[_]: Logger: Sync: Timer](topicAdminClient: TopicAdminClient, retryConfig: RetryConfig) extends GoogleTopicAdmin[F] {
Do we need tests for this class?

2019-03-11 13:03 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleTopicAdminInterpreter.scala
> +class GoogleTopicAdminInterpreter[F[_]: Logger: Sync: Timer](topicAdminClient: TopicAdminClient, retryConfig: RetryConfig) extends GoogleTopicAdmin[F] {
Ideally we would, but there's not much testing we can do without talking to actual google, which we don't want to do in unit tests

2019-03-12 03:26 UTC, ansingh7115 approved these changes

2019-03-12 04:05 UTC, merged