Add more functions to GoogleStorageService and bug fixes
broadinstitute/workbench-libs pull request #207
Opened 2019-03-14 15:14 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-03-15 02:25 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  def createBucketWithAdminRole(googleProject: GoogleProject, bucketName: GcsBucketName, adminIdentity: Identity, traceId: Option[TraceId] = None): Stream[F, Unit] = {
Would it be more flexible if this were broken into 2 functions, 1 to create the bucket and 1 to set IAM?

What identity requires `roles/storage.admin` access?

2019-03-15 02:25 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreatorInterpreter.scala
> +  def getStorageServer(project: GoogleProject, traceId: Option[TraceId]): F[Identity] = {
should this be called `getStorageServiceAccount`?

2019-03-15 05:06 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageNotificationCreatorInterpreter.scala
> +  def getStorageServer(project: GoogleProject, traceId: Option[TraceId]): F[Identity] = {
just saw the comment. Weird I don't see the email in gmail. I renamed it to `projectServiceAccount` (`the email address of the service account associated with the project that contains your Cloud Storage bucket` is how google describe it`). Let me know if this sounds good. I also renamed  `GoogleStorageNotification` to `GoogleServiceHttp` so that we can put anything that requires direct http call to this class.

2019-03-15 05:13 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  def createBucketWithAdminRole(googleProject: GoogleProject, bucketName: GcsBucketName, adminIdentity: Identity, traceId: Option[TraceId] = None): Stream[F, Unit] = {
I figured it's probably common that whoever created the bucket also wants admin role on the bucket, which is rawls does, so I bundled them together.
`roles/storage.admin` is given to `806222273987-ksinuueghug8u81i36lq8aof266q19hl@developer.gserviceaccount.com`, this is needed for it to create notification (it really only need ` storage.buckets.update` permission, but `roles/storage.admin` is the only existing role that has it I think).

2019-03-18 17:51 UTC, dvoet requested changes

2019-03-18 17:51 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +        Logger[F].info(s"$bucketName already exists")
I don't think we should be handling 409 here. That error should be passed up to the caller since this is a generic function.

2019-03-18 17:51 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      updatedPolicy = roles.foldLeft(policyBuilder)((curBuilder, item) => curBuilder.addIdentity(Role.of(item._1.name), item._2.head, item._2.tail: _*)).build()
no abbreviates please... what is cur in curBuilder?

2019-03-18 17:51 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  def createBucketWithRoles(googleProject: GoogleProject, bucketName: GcsBucketName, roles: Map[StorageRole, NonEmptyList[Identity]], traceId: Option[TraceId] = None): Stream[F, Unit] = {
I still think this should be 2 functions: `createBucket` (which we already have above) and `addBucketIamPolicy`. They seem pretty separate and usable independently. But at the very least `createBucketWithRoles` should call `createBucket`.

2019-03-18 17:51 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +    def retry[A]: (F[A], String) => Kleisli[Stream[F, ?], Option[TraceId], A] = (fa, str) => Kleisli(traceId => retryGoogleF(retryConfig)(fa, traceId, str))
what would the code be like without a `Kleisli`? Every time I see it I need to lookup what it is again.

2019-03-18 18:06 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  def createBucketWithAdminRole(googleProject: GoogleProject, bucketName: GcsBucketName, adminIdentity: Identity, traceId: Option[TraceId] = None): Stream[F, Unit] = {
the reason it is an all-in-one function call in rawls is that for legacy ACLs, the bucket can be created and ACLs set in a single google call. That doesn't appear to be the case in the new IAM model.

2019-03-18 23:49 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +        Logger[F].info(s"$bucketName already exists")
This is the concrete action of creating bucket. In what sense this is generic?
If I leave out `handleErrorWith`, it'll be in `retryStorageF`, which I think harder to read

2019-03-18 23:49 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +    def retry[A]: (F[A], String) => Kleisli[Stream[F, ?], Option[TraceId], A] = (fa, str) => Kleisli(traceId => retryGoogleF(retryConfig)(fa, traceId, str))
I'd have to pass `tradeId` to each `retryGoogleF` explicitly and it can easily get lost in one call.

2019-03-18 23:49 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      updatedPolicy = roles.foldLeft(policyBuilder)((curBuilder, item) => curBuilder.addIdentity(Role.of(item._1.name), item._2.head, item._2.tail: _*)).build()
It's the current builder. It's the accumulator for `foldLeft` function, each iteration it adds `addIdentity` to the current builder with initial builder being `policyBuilder`.

2019-03-20 14:54 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      _ <- retryStorageKleisli(
I now remember a problem we had with this pattern where getting the iam policy and later setting it each in their separate retry does not work. The pattern is meant to ensure only 1 modifier at a time. If another process updates IAM between the get and the set then the call to set will persistently fail.

Instead get and set should be wrapped in a single retry. If the get succeeds and the set fails the get needs to be retried as well.

And then we don't need `retryStorageKleisli` either :) as there is only 1 usage of it

2019-03-20 15:01 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +    def retry[A]: (F[A], String) => Kleisli[Stream[F, ?], Option[TraceId], A] = (fa, str) => Kleisli(traceId => retryGoogleF(retryConfig)(fa, traceId, str))
if you are worried about it getting missed in a call to `retryGoogleF` then don't give it a default value in `retryGoogleF`

2019-03-21 14:11 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      _ <- retryStorageKleisli(
updated

2019-03-25 13:32 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  private def retryStorageKleisli[A] = retryGoogleKleisli[F, A](retryConfig)
this is unused, please remove

2019-03-25 13:32 UTC, dvoet approved these changes
remove retryStorageKleisli then 👍

2019-03-25 16:58 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleServiceHttpInterpreter.scala
> +  def createNotification(topic: ProjectTopicName, bucketName: GcsBucketName, filters: Filters, traceId: Option[TraceId]): F[Unit] = {
Could you add a comment saying what a TraceId is? (somewhere it makes sense, maybe where its is defined)

2019-03-25 17:01 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleServiceHttpInterpreter.scala
> +      ).withEntity(notificationBody))(onError(traceId))
should we logging more than just the trace id here and in `getProjectServiceAccount`?

2019-03-25 17:10 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleServiceHttpInterpreter.scala
> +    val headers = Headers(Authorization(Credentials.Token(AuthScheme.Bearer, googleCredentials.refreshAccessToken().getTokenValue)))
`headers` is unused

2019-03-25 17:15 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +  private def retryStorageKleisli[A] = retryGoogleKleisli[F, A](retryConfig)
+1

2019-03-25 17:20 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +import cats.data.Kleisli
unused import

2019-03-25 17:25 UTC, ansingh7115 commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +    * @param traceId uuid for tracing a unique call flow in logging
Ah! I see you've defined it here - could you add the comment to the definition of TraceId?

2019-03-26 02:30 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleServiceHttpInterpreter.scala
> +      ).withEntity(notificationBody))(onError(traceId))
http header and body logging are enabled [here](https://github.com/broadinstitute/workbench-libs/pull/207/files#diff-87adb86e5a9c3c79b1467a69aa71e76fR25)

2019-03-26 18:47 UTC, ansingh7115 approved these changes

2019-03-27 04:35 UTC, merged