Rawls billing api
broadinstitute/workbench-libs pull request #209
Opened 2019-04-05 14:47 UTC by aweng98

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-04-05 14:49 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/BillingProject.scala
> +object BillingProject {
took it from `Orchestration.scala`.

2019-04-05 14:51 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/RestClient.scala
> +        // logger.info(s"API request: ${httpRequest}\nAPI response: ${response}")
reduce logs traffic

2019-04-05 15:16 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/RestClient.scala
> +        // logger.info(s"API request: ${httpRequest}\nAPI response: ${response}")
Don't remove this - we had an instance last week of someone using this to debug an issue and that likely wasn't the only instance of someone doing that

2019-04-05 15:48 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def waitUntilDoneBillingProject(projectName: String, billingAccount: String)(implicit token: AuthToken): Unit = {
This should be `private`

2019-04-05 15:53 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +      waitUntilDoneBillingProject(projectName, billingAccount)
I would change the name of this to `waitUntilBillingProjectIsReady`

2019-04-05 15:56 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/BillingProject.scala
> +  object Role extends Enumeration {
This should go back to being named `BillingProjectRole` - what was your reason for making it vaguer?

2019-04-05 16:25 UTC, ansingh7115 commented
This needs TRAVIS-REPLACE-MEs in readme and changelog

2019-04-05 16:31 UTC, ansingh7115 requested changes
This needs TRAVIS-REPLACE-MEs in readme and changelog first

2019-04-08 17:46 UTC, ansingh7115 approved these changes

2019-04-09 15:42 UTC, marctalbott approved these changes

2019-04-09 17:02 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def addUserToBillingProject(projectName: String, email: String, billingProjectRole: BillingProjectRole)(implicit token: AuthToken): String = {
Why was this changed from unit to string?

2019-04-09 17:30 UTC, marctalbott commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +  object methodconfigs {
The 'c' should be capitalized so it's `methodConfigs`

2019-04-09 17:30 UTC, marctalbott commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def getMethodConfigInWorkspace(workspaceNamespace: String, workspaceName: String, configNamespace: String, configName: String)(implicit token: AuthToken): HttpResponse = {
I'm not sure what the exact reason for this is, but typically we wrap `getRequest`s in `parseResponse` so that the return type of the function is a `String` as opposed to a `HttpResponse`. I'd guess that part of the reason is that `parseResponse` logs any errors and the `String` return type is easier to deal with than the `HttpResponse`. At any rate, I'd advise using `parseResponse` both in this function and for `getMethodConfigSyntaxValidationInWorkspace`

2019-04-09 17:30 UTC, marctalbott commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def createMethodConfigInWorkspace(wsNs: String, wsName: String, method:Method, configNamespace: String, configName: String, methodConfigVersion: Int,
`workspaceNamespace` instead of `wsNs` just for consistent parameter naming across these functions

2019-04-09 17:34 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def addUserToBillingProject(projectName: String, email: String, billingProjectRole: BillingProjectRole)(implicit token: AuthToken): String = {
test can work with string for values extraction if needed

2019-04-09 17:43 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def getMethodConfigInWorkspace(workspaceNamespace: String, workspaceName: String, configNamespace: String, configName: String)(implicit token: AuthToken): HttpResponse = {
I feel it's a correct usage because I'm checking for status code.
Usage:
```
val response: HttpResponse = Rawls.methodconfigs.getMethodConfigInWorkspace(billingProject, workspaceName, namespace, name)
      assertResult(StatusCodes.OK) {
        response.status
      }
```

2019-04-09 17:59 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def getMethodConfigInWorkspace(workspaceNamespace: String, workspaceName: String, configNamespace: String, configName: String)(implicit token: AuthToken): HttpResponse = {
also because `def getRequest` returns `HttpResponse` in `RestClient.scala`, not `String`

2019-04-09 18:03 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +          "prerequisites" -> Map(),
any diff between `Map()` and `Map.empty`? one is better to use than other?

2019-04-09 18:15 UTC, marctalbott commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +          "prerequisites" -> Map(),
I believe there is no difference, and I don't personally have any preference between the two, but maybe some people do?

2019-04-09 18:26 UTC, marctalbott commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def getMethodConfigInWorkspace(workspaceNamespace: String, workspaceName: String, configNamespace: String, configName: String)(implicit token: AuthToken): HttpResponse = {
For what it's worth, `parseResponse` will throw a `RestException` if the response is not successful, so you wouldn't have to check that the status code was 200. That being said, I don't know enough about this to definitively say that `parseResponse` is the right way to go. I also see that there is at least one other function that returns an HttpResponse (`getObjectDownload` in Orchestration), so this isn't unprecedented either which is what I initially thought.

2019-04-09 19:58 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +  object methodconfigs {
changed

2019-04-09 19:59 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def getMethodConfigInWorkspace(workspaceNamespace: String, workspaceName: String, configNamespace: String, configName: String)(implicit token: AuthToken): HttpResponse = {
updated `getMethodConfigInWorkspace` to return a `String` instead `HttpResponse`. 
new usage:
```
val response = Rawls.methodConfigs.getMethodConfigInWorkspace(billingProject, workspaceName, namespace, name)
val parsedStr = response.parseJson.asJsObject.getFields("methodRepoMethod")
parsedStr should not be empty
```

2019-04-09 20:00 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def createMethodConfigInWorkspace(wsNs: String, wsName: String, method:Method, configNamespace: String, configName: String, methodConfigVersion: Int,
changed

2019-04-09 20:52 UTC, merged