Return blob
broadinstitute/workbench-libs pull request #244
Opened 2019-06-18 17:54 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2019-06-19 15:37 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +import scala.concurrent.ExecutionContext.global
Why is it needed to import the implicit global execution context -- I thought methods in the interpreter allow the caller to pass an execution context?

2019-06-19 15:43 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +import scala.concurrent.ExecutionContext.global
Oh I misread, this isn't importing the implicit (which is `scala.concurrent.ExecutionContext.Implicits.global`) and is just used as a default arg lower down. So I think this is fine

2019-06-19 15:47 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +  def getBlob(bucketName: GcsBucketName, blobName: GcsBlobName, traceId: Option[TraceId] = None): Stream[F, Blob]
Why would I use `getBlob` over `getObjectBody`? Some javadoc would be nice.

2019-06-19 15:50 UTC, rtitle approved these changes
Looks good to me

2019-06-19 19:36 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageService.scala
> +  def getBlob(bucketName: GcsBucketName, blobName: GcsBlobName, traceId: Option[TraceId] = None): Stream[F, Blob]
`Blob` is `com.google.cloud.storage.Blob`, which comes from the java lib. The original `getObjectBody` only returns the object body. But `Blob` actually exposes lots of extra things like metadata etc, so providing this method is handy so that we don't have to write a different method for each different thing we need out of blob

I'll add some doc

2019-06-19 20:48 UTC, dvoet requested changes
I think the only backwards incompatible changes are renaming the getObject functions. Instead of renaming, deprecate the old name then you don't need a minor version bump

2019-06-19 21:07 UTC, Qi77Qi commented
@dvoet I also bumped http4s's version, I think it's safer to always bump minor when we upgrade dependency

2019-06-20 12:48 UTC, dvoet commented
@Qi77Qi I am not certain I agree... if the dependency upgrade is backwards compatible why would we say our library is not? Why is it safer to bump the minor version when updating a dependency when a minor version bump in workbench-lib is supposed to signify a break in compatibility?

2019-06-20 15:11 UTC, Qi77Qi commented
@dvoet ,

1.  If we don't want to bump minor, I'll have to add `@deprecate` on `storeObject` as well. (potentially there're other things I missed)
2.  I don't quite like using `@deprecation` here because it's more meaningful if we can specify since what version, but since we're using hash cross bin compact versions, this field is meaningless(imagine you see "deprecation since `v1-someHash`" while you have `vs-someOtherHash`)
3. I've had a few cases where I had to delete deprecation annotation or another case deleting the old renamed method.
4. If we use deprecation here, is bumping minor version a good time to remove them? Or what's appropriate time removing them?

2019-06-20 17:56 UTC, dvoet commented
I agree that hashes do not really work as version numbers (we are seeing other problems where sbt evicts the newer version because is comes later in the alphabet).

I am just trying to stick to the guidelines as stated. If the guidelines need to be updated then we should do that.

Even if we don't change the use of hashes in versions, I think a deprecation tag is better than nothing as we should strive to avoid incompatible changes.

2019-06-20 17:58 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +                           objectType: String = "text/plain",
why add this default?

2019-06-20 18:01 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +      blockingEc: ExecutionContext,
why change the name to be less descriptive... we should avoid abbreviations

2019-06-20 19:05 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleStorageInterpreter.scala
> +                           objectType: String = "text/plain",
mostly because I haven't seen any other values being used.

2019-06-21 13:15 UTC, dvoet approved these changes

2019-06-21 13:17 UTC, merged