[no ticket] add traceId in published messages
broadinstitute/workbench-libs pull request #280
Opened 2020-02-03 22:03 UTC by Qi77Qi

1. add `traceId` in published messages in publisher
2. extract `traceId` and log it in subscriber
3. Use `StructuredLogger` instead of `Logger`...(this shouldn't cause issue for caller since `Slf4jLogger.getLogger[IO]` is a `StructuredLogger` 

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2020-02-03 22:31 UTC, jdcanas requested changes
I don't think this compiles due to https://github.com/broadinstitute/workbench-libs/blob/5f6963ecf42d1e1fa6f89361c4af6bdf11dad795/google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleDataproc.scala#L40

2020-02-03 22:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleDataproc.scala
> +      .setCredentialsProvider(FixedCredentialsProvider.create(serviceAccountCredentchials))
typo

2020-02-03 22:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def tracedPublish[MessageType: Encoder]: Pipe[F, Message[MessageType], Unit]
does this really need to be another method in the interface? I might be missing something, but It seems like this could with an optional parameter, and then it would still be a non-breaking change.

2020-02-03 22:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            StructuredLogger[F].info(loggingCtx)(s"failed to enqueue $message to internal Queue due to $e") >> Effect[F].delay(consumer.nack()) //pubsub will resend the message up to ackDeadlineSecon
nit: does this comment reference the correct field in the RetryConfig?

2020-02-03 22:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            StructuredLogger[F].info(loggingCtx)(s"successfully to enqueue $message")
something like 'successfully enqueued $message' reads better imo

2020-02-03 22:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +final case class LoggableGoogleCall(response: Option[String], result: String)
Result seems to be a case class with two options, 'success' or 'failure'. I'd either refactor it, or, if you wish to keep the encoder/decoder simple, add a comment here indicating its current usage.

2020-02-04 03:00 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisher.scala
> +  def tracedPublish[MessageType: Encoder]: Pipe[F, Message[MessageType], Unit]
we will need a separate function, because `Pipe[F[_], I, O]` is just type alias of `Stream[F, I] => Stream[F, O]`, what we want is `Stream[F, Message] => Stream[F, Unit]`, not `Message => Stream[F, I] => Stream[F, Unit]`

2020-02-04 03:03 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            StructuredLogger[F].info(loggingCtx)(s"failed to enqueue $message to internal Queue due to $e") >> Effect[F].delay(consumer.nack()) //pubsub will resend the message up to ackDeadlineSecon
are you referring to a different line?

2020-02-04 03:07 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +final case class LoggableGoogleCall(response: Option[String], result: String)
I don't think it's needed to make this ADT since it's just for logging and no caller elsewhere will be consuming the info

2020-02-04 14:47 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +            StructuredLogger[F].info(loggingCtx)(s"failed to enqueue $message to internal Queue due to $e") >> Effect[F].delay(consumer.nack()) //pubsub will resend the message up to ackDeadlineSecon
In this comment, `//pubsub will resend the message up to ackDeadlineSeconds` , it seems to be referring to the `maxAttempts` field as opposed to the `ackDeadlineSeconds` second field based on the wording.

2020-02-04 14:50 UTC, jdcanas approved these changes

2020-02-05 04:01 UTC, rtitle approved these changes
Lgtm

2020-02-05 04:01 UTC, rtitle commented on google2/CHANGELOG.md
> +- Use `io.chrisdavenport.log4cats.StructuredLogger` instead of `io.chrisdavenport.log4cats.Logger`
Remove this from 0.6?

2020-02-06 15:41 UTC, dvoet commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +        msg = message.msg.asJson.deepMerge(extraInfo.asJson) //decorate the message with extra info
Embedding the extra information in message itself seems problematic to me because it means the consumer must deal with it. It also eats into the the max message size (granted the max message size is 10MB and this little bit of data probably won't be noticed).

Did you consider user message attributes instead? Also the publish time is automatically included in the message by Google. See https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage

2020-02-07 16:09 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleSubscriberInterpreter.scala
> +              r <- queue.enqueue1(event).attempt
So do we think this error handling will resolve the message-not-received issue?

2020-02-07 16:43 UTC, Qi77Qi commented
@rtitle , I think previously the message was received. It's just the error was thrown and somehow didn't show in log. I see error log when this happens in my manual test https://github.com/broadinstitute/workbench-libs/pull/280/files#diff-161d25ff3e7b79c4cd2e1c5deca0027aR49 ....But in leo, error was never shown when I publish bad messages to the topic. After this PR, we'll see errors.

2020-02-07 16:56 UTC, kyuksel commented
Curious if you found out anything that may explain seeing the issue in dev and not Justin's fiab  🤔

2020-02-07 19:58 UTC, Qi77Qi commented
@kyuksel needs a little more testing..but I think https://github.com/DataBiosphere/leonardo/pull/1271 is the real fix why fiab works but not in dev...it's user error

2020-02-07 20:03 UTC, Qi77Qi commented
talked to @dvoet this morning...I think he's okay with merging

2020-02-07 20:03 UTC, merged