Jc gke
broadinstitute/workbench-libs pull request #287
Opened 2020-03-10 17:13 UTC by jdcanas

Putting this in a bit early to get some feedback

This PR
- adds a google service to interact with GKE
   - can create Clusters/Nodepools
- Adds a service to interact with kubernetes API
   - Allows creation of a namespace
   - Allows creation of a service (which allows containers to be exposed externally to the cluster)
   - Allows creation of a Pod with a set of containers on the Pod 
   - Allows mapping between a service and a pod
 - lays the foundation for unit testing the above to via a test object

TODO list:
- add blocker/semaphore usage
- retry where applicable

2020-03-10 17:14 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +object Test {
this is mainly for local testing of these APIs

2020-03-10 17:16 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +    fileReader <- Resource.make(
I really don't like surrounding this as a resource because it will never get released, and it can be closed before the KubernetesInterpreter is even created...

2020-03-10 17:17 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +  val DEFAULT_SERVICE_NAME = KubernetesServiceName("default-service")
this 'default_service' is used for pods that don't need any user-specific networking, and we just wish to expose to the internet

2020-03-10 17:22 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +  val kubeService = KubernetesService.resource("/Users/jcanas/Downloads/kube-broad-dsde-dev-key.json", "/Users/jcanas/.kube/config", Set(cluster2Id))
if you want to run this locally, you should only have to change the above hardcoded strings, and pick a `clusterName` that is not already created

2020-03-12 13:17 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/util/ReplacedGCPAuthenticator.java
> +// It is taken from https://github.com/kubernetes-client/java/issues/290#issuecomment-480205118
this isn't used currently, but its here in case we find it relevant

2020-03-12 13:22 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  def createNamespace(namespace: KubernetesNamespace): F[Unit]
the Kubernetes client is a bit simple and just returns the java object you give it to create, which I found not very useful, so these just return Unit

2020-03-17 19:32 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +   override def createCluster(kubernetesClusterRequest: KubernetesCreateClusterRequest)
Would it be cleaner for this method to take a `(project: GoogleProject, zone: ZoneName, cluster: com.google.container.v1.Cluster)`?

I feel like we don't need to rebuild all the input fields in `KubernetesCreateClusterRequest` -- the caller can be responsible for creating their own `Cluster` object. This is the pattern that the GCE service/interpreter uses.

2020-03-17 19:36 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +  //should clusters be created per project, or per user for billing?
In GKE clusters are per (project, location), so the wb-libs API should reflect that.

https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters/create

2020-03-17 19:36 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +object Test {
+1 should move to a unit test

2020-03-17 19:37 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  (implicit ev: ApplicativeAsk[F, TraceId]): F[Unit]
Might be good to run `scalafmt` on this :)

2020-03-17 19:39 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +      case e: ApiException => Async[F].delay(println(e.getResponseBody()))
Maybe add a `Logger` context bound and use that instead of `println`

2020-03-17 19:40 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +      for {
Minor, you can omit this `for`, this is equivalent:
```
Async[F].delay(kubernetesClient.createNamespacedPod(namespace.name.value, pod.getJavaSerialization, null, null, null)).void
```

2020-03-17 19:43 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  private def getKubernetesApiWithGoogleCreds[F[_] : Async](credentials: GoogleCredentials): F[CoreV1Api] = {
Is this used anywhere?

2020-03-17 19:45 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/util/ReplacedGCPAuthenticator.java
> +// It is taken from https://github.com/kubernetes-client/java/issues/290#issuecomment-480205118
Probably want to remove this before merge

2020-03-17 19:47 UTC, rtitle commented
Neat. There's still some cleanup to do before this is mergeable, but the overall structure looks good. I'm going to try and play around with it myself tonight, in particular the auth piece to try and better understand what's going on

2020-03-20 19:38 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +   override def createCluster(kubernetesClusterRequest: KubernetesCreateClusterRequest)
I changed it, but I feel it is still valuable to provide an easy way to get a 'defaultCluster'. Clusters are pretty complex, and it doesn't sound like we have any requirements to allow users to tune their cluster specs, so in an ideal world I would like all the guts of the objects used by in the google package hidden away in wb-libs

2020-03-24 13:07 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +  override def getCluster(clusterId: KubernetesClusterId)(implicit ev: ApplicativeAsk[F, TraceId]): F[Cluster] =
We often use the pattern of `getXxx` returning an `Option`, so it can return `None` instead of throw 404 when the object doesn't exist. For example here's the GCE `getInstance` implementation:
```
override def getInstance(project: GoogleProject, zone: ZoneName, instanceName: InstanceName)(
    implicit ev: ApplicativeAsk[F, TraceId]
  ): F[Option[Instance]] = {
    val projectZoneInstanceName = ProjectZoneInstanceName.of(instanceName.value, project.value, zone.value)
    retryF(
      recoverF(
        Async[F].delay(instanceClient.getInstance(projectZoneInstanceName)),
        whenStatusCode(404)
      ),
      s"com.google.cloud.compute.v1.InstanceClient.getInstance(${projectZoneInstanceName.toString})"
    )
  }
```

2020-03-24 13:10 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +  ): F[Operation]
This may be for a future PR, but for GCE I added some `Operation`-polling logic to `GoogleComputeService/Interpreter`. GCE and GKE have separate `Operation` objects, but maybe some of the polling logic could be reused/abstracted and used here too.

2020-03-24 13:13 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +      clusterManager <- Resource.make(
I think I added a utility for these clients -- could this be 
```
clusterManager <- resourceF(ClusterManagerClient.create(clusterManagerSettings))
```
?

2020-03-24 13:14 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  //namespaces group resources, and allow our list/get/update API calls to be segmented. This can be used on a per-user basis, for example
for example what? haha don't leave me hanging

2020-03-24 13:16 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  def createNamespace(clusterId: KubernetesClusterId, namespace: KubernetesNamespace)(
Eventually will we need getters for namespaces/pods/service?

2020-03-24 13:17 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +      scopedCredential = credentials.createScoped(Seq(ContainerScopes.CLOUD_PLATFORM).asJava)
Minor - are there more restrictive scopes we could use instead of `CLOUD_PLATFORM`?

2020-03-24 13:25 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +    clientOpt match {
I was wondering if a guava cache with a loading function could be used for this… but this implementation seems fine I think.

2020-03-24 13:30 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +  private val clientStore = TrieMap[KubernetesClusterId, ApiClient]()
This is a nice of use of state, and an elegant way of avoiding shelling out to connect with k8s.

I was debating with myself whether it's better to keep the state here in wb-libs code, or make the caller responsible for handling its own state. Generally wb-libs is stateless but in this case I think it's reasonable to have the state here because of the low-level details necessary for creating a k8s client (getting the certificate, token, etc).

So 👍

2020-03-24 13:39 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
I don't really like using a trait for this kind of validation.. would prefer something like:
```
final case class KubernetesName(value: String) extends AnyVal
object KubernetesName {
  def fromString(str: String): KubernetesName = /* do regex validation */
}
```

2020-03-24 13:42 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +final case class Parent(project: GoogleProject, location: Location) {
We have `RegionName` as well which I feel is more specific than `Location` -- if this should represent a region then could we use `RegionName`?

2020-03-24 13:43 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +final case class Parent(project: GoogleProject, location: Location) {
Enh, I just saw the below lines that GKE expects `../locations/..`. This is probably fine then.

I just wish GCP was consistent with itself ;)

2020-03-24 13:44 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +final case class KubernetesClusterName(value: String) extends KubernetesNameValidation
Maybe we should rename the current `ClusterName` to `DataprocClusterName` 🤔

2020-03-24 13:49 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +final case class KubernetesLoadBalancerService(selector: KubernetesSelector,
It's often a good practice to put ADT definitions instead the trait's companion object:
```
sealed trait Foo extends Product with Serializable {
  def type: String
  def name: String
}
object Foo {
  final case class Bar(name: String) extends Foo {
    override val type: String = "bar"
  }
  final case class Baz(name: String) extends Foo {
    override val type: String = "baz"
  }
}
```

2020-03-24 13:50 UTC, rtitle commented on google2/src/test/scala/org/broadinstitute/dsde/workbench/google2/KubernetesManualTest.scala
> +//TODO: investigate running minikube in a docker for unit/automation tests https://banzaicloud.com/blog/minikube-ci/
👍 .. maybe we could have tickets for these. Still useful to have a manual test here.

2020-03-24 13:52 UTC, rtitle approved these changes
See comments/questions above.. but in general this looks great. Thumbing for now, assuming we will iterate on this as time goes on.

Question.. does this require a version bump? Probably not as we're just adding new classes. Please update the `google2/CHANGELOG.md` regardless though to note the addition of the k8s clients.

2020-03-24 14:16 UTC, Qi77Qi requested changes

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesService.scala
> +object Test {
things for test shouldn't live in main code...you can move this to `test` and it'll still be available to applications if they decide to include it

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +class KubernetesInterpreter[F[_]: Async: StructuredLogger: Timer: ContextShift](
shall we abbreviate to `GkeInterpreter`? `KubernetesInterpreter` is really long

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +                                                                        pathToCredential: String,
I know you copied from previous code, but these paths should really be `java.nio.file.Path`

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  private def performGKEtoKubernetesCLIAuthHandoff[F[_] : Async](pathToCredential: String,  clusterIds: Set[KubernetesClusterIdentifier]): F[Unit] =
what is this function for?

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +  override def getCluster(clusterId: KubernetesClusterId)(implicit ev: ApplicativeAsk[F, TraceId]): F[Cluster] =
+1 we shouldn't throw 404 in a library. It should be up to caller what the action is when the cluster doesn't exist

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +      )
```
private def retryF[A](fa: F[A], loggingMsg: String)(implicit ev: ApplicativeAsk[F, TraceId]): F[A] =
   tracedRetryGoogleF(retryConfig)(blockerBound.withPermit(blocker.blockOn(fa)), loggingMsg).compile.lastOrError
```
We shouldn't wrap the whole retry inside `blockOn`, we should give `blockOn` the exact `F[A]` that you want to run on the blocking execution context

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +    credentials.refreshIfExpired()
this `refreshIfExpired` is side effecting, hence it should be in `F`

2020-03-24 14:16 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +    blockerBound.withPermit(
use retry

2020-03-24 23:22 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  def createNamespace(clusterId: KubernetesClusterId, namespace: KubernetesNamespace)(
I don't know if we will ever need getters for those, I think we can save the information we used to create them if we need that as state in leo. If that's the case, I'd probably update the return of the create from F[Unit] to some helpful object. 

In other words, I don't know an exact use case for getters, so they may be needed but I'd prefer to defer until we find a use case.

2020-03-24 23:28 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +  private val clientStore = TrieMap[KubernetesClusterId, ApiClient]()
Yeah, its 'loose' state, almost more of a cache, since at any time the program can restart, and the worst that will happen is we will need to perform the getCluster google call again and reconstruct the client. 

We technically don't have to store it, google holds all the information so we could either 1) call google every time we want to interact with the cluster or 2) store it in a DB, but I like doing this and holding it in memory since storing it in a DB would involve saving a certificate, and calling google repeatedly has performance overhead

2020-03-24 23:31 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
Hmm... the reason I did it like this was because of the mobbing we did where @Qi77Qi mentioned that she assumes that the data in a case class is validated at the time of construction. I kind of like that assumption, as otherwise the validation error is pushed further downstream and a bit harder to reason about. 

To me, it makes more sense that it errors out at instantiation as opposed to when you try to use the data. There could be a more elegant way to implement that than a trait though

2020-03-24 23:35 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +    blockerBound.withPermit(
I defer retrying, since I'm not sure what exactly we want to retry in the context of the kubernetes client as opposed to the google client, which has fairly established retry predicates in wb-libs. I leave a comment above the retry config param, since we will need to reconstruct the predicates to handle the relevant kubernetes client codes

2020-03-25 12:55 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
Maybe something like this?
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

val regex = "(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)".r

final case class KubernetesName private (value: String) extends AnyVal

object KubernetesName {
  def apply(value: String): KubernetesName = 
    if (regex.pattern.matcher(value).matches()) new KubernetesName(value)
    else throw new Exception("regex doesn't match")
}

// Exiting paste mode, now interpreting.

regex: scala.util.matching.Regex = (?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)
defined class KubernetesName
defined object KubernetesName

scala> KubernetesName("foo")
res0: KubernetesName = KubernetesName(foo)

scala> KubernetesName("Foo")
java.lang.Exception: regex doesn't match
  at KubernetesName$.apply(<pastie>:21)
  ... 29 elided
```

I think my main objection boils down to this validation being a _behavior_ not a _type_, so I don't like having a trait dedicated to this purpose.

2020-03-25 13:13 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GoogleKubernetesInterpreter.scala
> +      )
so are you saying 

```
    blockerBound.withPermit(
      blocker.blockOn(
        tracedRetryGoogleF(retryConfig)(fa, action).compile.lastOrError
      )
    )
```

turns into this (pre scalafmt)

```
    tracedRetryGoogleF(retryConfig)(
      blockerBound.withPermit(
        blocker.blockOn(fa)
      ),
      action).compile.lastOrError
```

2020-03-25 13:14 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +  private def performGKEtoKubernetesCLIAuthHandoff[F[_] : Async](pathToCredential: String,  clusterIds: Set[KubernetesClusterIdentifier]): F[Unit] =
its removed in a recent revision

2020-03-25 13:21 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesService.scala
> +      scopedCredential = credentials.createScoped(Seq(ContainerScopes.CLOUD_PLATFORM).asJava)
I don't think there are based on this https://developers.google.com/identity/protocols/oauth2/scopes

2020-03-25 13:40 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +final case class KubernetesClusterName(value: String) extends KubernetesNameValidation
Hmm.. I think it should be done but in a separate PR as it will make this require a version bump

2020-03-26 20:38 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
Hmm.. I would be ok with this approach if we could simplify all Names to KubernetesName, but I think there is value in having multiple case classes for each type of Kubernetes name for type safety. This validation is also used for some GKE names as well as kubernetes client names. It seems cumbersome to have a companion object and apply for all names related to these two services.

I found a method `require`, which based on the [documentation](https://www.scala-lang.org/api/current/scala/Predef$.html) seems to be for this exact purpose. I really like the flexibility that the trait gives us over a companion object for many private case classes, since this validation applies to both GKEModels and KubernetesModels.

2020-03-27 12:51 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +                throw KubernetesClusterNotFoundException(
Avoid `throw`, I would do something like this:
```
         val res = for {
            _ <- StructuredLogger[F]
              .info(s"Determined that there is no cached client for kubernetes cluster ${clusterId}. Creating a client")
            clusterOpt <- gkeService.getCluster(clusterId)
            cluster <- clusterOpt.fold(
              Async[F].raiseError[Cluster](KubernetesClusterNotFoundException(
                s"Could not create client for cluster ${clusterId} because it does not exist in google")
              ))(Async[F].pure)
            token <- getToken
            client <- createClient(cluster, token)
          } yield client
```

2020-03-27 12:54 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +  def streamFUntilDone[F[_]: Timer, A, B <: DoneCheckable](fa: F[A],
Nice

2020-03-27 12:56 UTC, rtitle commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
Ok, I can buy this

2020-03-27 12:57 UTC, rtitle commented on google2/CHANGELOG.md
> +- Add `GKEInterpreter`, `GKEService`, `KubernetesService`, and `KubernetesInterpreter`
Can you put this in the `Added` section?

2020-03-27 12:57 UTC, rtitle commented on google2/CHANGELOG.md
> +- Add `GKEInterpreter`, `GKEService`, `KubernetesService`, and `KubernetesInterpreter`
Also maybe note the dependencies added

2020-03-27 12:58 UTC, rtitle commented
Nice! Just a couple more comments above, this is looking great though

2020-03-27 13:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +                throw KubernetesClusterNotFoundException(
👍 on not throwing...you can do something like this as well
```
Async[F].fromEither(clusterOpt.toRight(KubernetesClusterNotFoundException(
      s"Could not create client for cluster ${clusterId} because it does not exist in google")
    ))
```

2020-03-27 15:29 UTC, Qi77Qi requested changes

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GKEInterpreter.scala
> +    val opString = operationId.idString
remove this line

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GKEInterpreter.scala
> +    //TODO: remove below before merge, just displaying the alternative
remove commented out code

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +}
I would do typeclass pattern like this:

```
trait DoneCheckable[A] {
  def isDone(a: A): Boolean
}

object DoneCheckableInstances {
  implicit val containerDoneCheckable = new DoneCheckable[com.google.container.v1.Operation]{
    def isDone(op: com.google.container.v1.Operation): Boolean = op.getStatus == "DONE"
  }
  implicit val computeDoneCheckable = new DoneCheckable[com.google.cloud.compute.v1.Operation]{
    def isDone(op: com.google.cloud.compute.v1.Operation): Boolean = op.getStatus == "DONE"
  }
}

final case class DoneCheckableOps[A: DoneCheckable](a: A) {
  def isDone: Boolean = implicitly[DoneCheckable].isDone(a)

}

object DoneCheckableSyntax {
  implicit def doneCheckableSyntax[A](a: A): DoneCheckableOps[A] = DoneCheckableOps(a)
}
```

This way, you won't need `GKEPollOperation`  and `PollOperation`, and at call site, once you `import DoneCheckableSyntax._`, you'll be able to call `isDone` on regular `com.google.cloud.compute.v1.Operation` and `com.google.container.v1.Operation`

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +trait KubernetesNameValidation {
I like what Rob suggested as well, but with slight change
```
final case class KubernetesName(value: String) extends AnyVal
object KubernetesName {
  def fromString(str: String): Either[Throwable, KubernetesName] = /* do regex validation */
}
```
notice it should return `Either`

also `require` throws exception

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +    def parentString: String = s"projects/${project.value}/locations/${location.value}"
use `val`

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +    def idString: String = s"projects/${project.value}/locations/${location.value}/operations/${operation.getName}"
use `val`

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +sealed trait KubernetesSerializable extends Product with Serializable {
why is this needed?

2020-03-27 15:29 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +    val base64Cert = Base64.decodeBase64(value)
`val base64Cert = Either.catchNonFatal(Base64.decodeBase64(value)`

2020-03-27 15:30 UTC, Qi77Qi commented
overall looks good 👍 ..a few more questions

2020-03-27 19:14 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/kubernetesModels.scala
> +sealed trait KubernetesSerializable extends Product with Serializable {
It defines the interface for all Kubernetes ADTs to get the java representation for use with the client library. Its useful because a lot of the Kubernetes objects have nested components, and this allows them serialize any subcomponents with a common interface. 

Additionally, there are scenarios where subclasses use polymorphism to get more specific. For example, `KubernetesServiceKind` is a trait that extends this trait, and there are a few type of services in Kubernetes that are concrete implementations

2020-03-27 19:45 UTC, jdcanas commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +}
I see the value in removing the map step and making a doneWrapper with implicits, but I think the non-type classed trait with case classes approach provides more flexibility and readability. 

1) the flexibility of being able to specify any number of parameters to a case class allows for more complex computations of 'done' as long as the result is a boolean, while type classing does not allow for a variable number of parameters 
2) in terms of readability, I feel the syntax of ` def streamFUntilDone[F[_]: Timer, A, B <: DoneCheckable]` requires a bit of unwrapping, and the use of implicits further obfuscates the intent

2020-03-27 19:47 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/package.scala
> +}
let's jump on a call

2020-03-30 22:12 UTC, Qi77Qi approved these changes
👍 lgtm

2020-03-30 22:12 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/KubernetesInterpreter.scala
> +  //TODO: retry once we know what kubernetes codes are applicable
remove todo

2020-03-31 13:56 UTC, rtitle commented on google2/CHANGELOG.md
> +## 0.8
If you're bumping to 0.8 you need to update `Settings.scala`, I didn't see that in the PR

2020-03-31 14:06 UTC, rtitle approved these changes

2020-04-02 13:45 UTC, dvoet approved these changes

2020-04-02 14:37 UTC, merged