[wip] add openTelemetry module
broadinstitute/workbench-libs pull request #291
Opened 2020-03-26 02:35 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2020-03-30 13:54 UTC, kyuksel approved these changes
LGTM 👍 Minor comments inline.

2020-03-30 13:54 UTC, kyuksel commented on openTelemetry/README.md
> +`scala> res0.unsafeRunSync()`
Thank you for adding this!

2020-03-30 13:54 UTC, kyuksel commented on project/Dependencies.scala
> +//  val openTelemetry: ModuleID = "io.opentelemetry" % "opentelemetry-sdk" % "0.2.4"
Do we need ^^ ?

[Here](https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md) it says 

> Libraries that want to export telemetry data using OpenTelemetry MUST only depend on the opentelemetry-api package and should never configure or depend on the OpenTelemetry SDK.

2020-03-30 13:54 UTC, kyuksel commented on openTelemetry/CHANGELOG.md
> +This file documents changes to the `workbench-openTelemetry` library, including notes on how to upgrade to new versions.
Mention `scalaVersion` change too?

2020-03-30 13:59 UTC, Qi77Qi commented on project/Dependencies.scala
> +//  val openTelemetry: ModuleID = "io.opentelemetry" % "opentelemetry-sdk" % "0.2.4"
yea, this is not needed...will remove

2020-03-30 14:10 UTC, Qi77Qi commented on openTelemetry/CHANGELOG.md
> +This file documents changes to the `workbench-openTelemetry` library, including notes on how to upgrade to new versions.
it's a minor bump for all published libraries...I'm not sure if it belongs in a particular module's changelog, but it also doesn't matter to user since it's a scala minor version bump

2020-03-31 14:32 UTC, rtitle requested changes
If we're scalafmt-ing the whole repo I think it should probably be done in its own PR. Could format just the new module for now.

2020-03-31 15:58 UTC, Qi77Qi commented
@rtitle I think I'll leave the scalafmt commit in since I might have other stuff amended into that commit

2020-03-31 21:54 UTC, merged