wip adding headless chrome option enable dev shm
broadinstitute/workbench-libs pull request #326
Opened 2020-07-01 19:57 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2020-07-01 23:17 UTC, xuscrbw approved these changes
lgtm

2020-07-02 00:57 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    //options.addArguments("--disable-dev-shm-usage")
Why is this not needed?

2020-07-02 00:57 UTC, aweng98 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    }
Additional chrome flags for consideration to add that can improve perf and reduce chrome memory footprint.
```
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-breakpad",
    "--disable-component-extensions-with-background-pages",
    "--disable-features=TranslateUI,BlinkGenPropertyTrees",
    "--disable-ipc-flooding-protection",
    "--disable-renderer-backgrounding",
    "--enable-features=NetworkService,NetworkServiceInProcess",
    "--force-color-profile=srgb",
    "--hide-scrollbars",
    "--metrics-recording-only",
    "--mute-audio",
```

2020-07-02 12:55 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    }
ah cool...I can try adding these...is this from some doc? just curious to read more about this

2020-07-02 12:55 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +    //options.addArguments("--disable-dev-shm-usage")
I made this change https://github.com/broadinstitute/firecloud-automated-testing/commit/3aa9366d1e594712a851be15224a919cf85209ee#diff-ee957fa1c3e182008433fcf99d1617cfL78...so was thinking we don't need this flag anymore

2020-07-02 15:06 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> -        driver.manage.window.setSize(new org.openqa.selenium.Dimension(2880, 1800))
removing this since we're already adding it in chromeOptions

2020-07-07 22:27 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserUtil.scala
> +//      val duration = Duration.ofSeconds(timeOutInSeconds)
commenting this out for now since when we upgrade to selenium 4+, this will be needed

2020-07-07 22:33 UTC, aweng98 requested changes

2020-07-07 22:33 UTC, aweng98 commented on project/Dependencies.scala
> -  val selenium: ModuleID = "org.seleniumhq.selenium" % "selenium-java" % "4.0.0-alpha-6" % "test"
I think run test in non-docker will fail without selenium downloaded. so selnium-java is still needed. use stable release.

2020-07-07 23:41 UTC, Qi77Qi commented on project/Dependencies.scala
> -  val selenium: ModuleID = "org.seleniumhq.selenium" % "selenium-java" % "4.0.0-alpha-6" % "test"
`"org.scalatestplus" %% "selenium-3-141" % "3.2.0.0" ` is already bringing selenium transitively..so it should be fine...I'd prefer not to duplicate it here just because I was confused earlier thinking we were using selenium 4.+, but that wasn't the case when we're using scalatest-selenium because `scalatestplus` brings in a different version

2020-07-08 00:52 UTC, aweng98 approved these changes

2020-07-08 12:06 UTC, merged

2020-07-08 19:29 UTC, Qi77Qi commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserSpec.scala
> +        "profile.block_third_party_cookies" -> false
this is the real fix