[GAWB-2648] Leo call sam to create pet service account at cluster creation time
broadinstitute/workbench-libs pull request #33
Opened 2017-10-21 01:34 UTC by rtitle

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2017-10-21 01:53 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchPerson {
`WorkbenchPerson` is a supertrait of `WorkbenchUser` and `WorkbenchUserServiceAccount`

2017-10-23 14:54 UTC, helgridly approved these changes
nits

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def addIamRolesForUser(googleProject: String, userEmail: WorkbenchEmail, rolesToAdd: Set[String]): Future[Unit]
We don't have value classes for `GoogleProject`? :o

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +  override def addIamRolesForUser(googleProject: String, userEmail: WorkbenchEmail, rolesToAdd: Set[String]): Future[Unit] = {
nit: could do with a comment to indicate that the project is the one in which you want to add the IAM roles

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +  override def addServiceAccountActorRoleForUser(googleProject: String, serviceAccountEmail: WorkbenchUserServiceAccountEmail, userEmail: WorkbenchEmail): Future[Unit] = {
this could do with a comment too imo

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    * Read-modify-write a Policy to insert or remove new bindings for the given member and roles.
Could this get racy?

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    * Read-modify-write a Policy to insert or remove new bindings for the given member and roles.
Actually, nothing we could do about it here; the lock would need to be global on the IAM end. Let's hope Goog has some good error handling.

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    * Read-modify-write a Policy to insert or remove new bindings for the given member and roles.
I take it there's no way to simply add a policy instead of replacing the entire list?

2017-10-23 14:54 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    // Note that if the same role is in both rolesToAdd and rolesToRemove, the deletion takes precedence.
Seems like an important point. You should probably roll this up into at least the top-level comment for this function; if there are others that call this with both add and remove, add the note there too

2017-10-23 14:54 UTC, helgridly commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchPerson {
nit: maybe `WorkbenchIdentity` is a better name, given that service accounts aren't people

(cue my house being firebombed by People for the Ethical Treatment of Service Accounts)

2017-10-23 15:02 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def addIamRolesForUser(googleProject: String, userEmail: WorkbenchEmail, rolesToAdd: Set[String]): Future[Unit]
We do in Leo, not in workbench-libs. It seems generic enough to move to workbench-libs.

2017-10-23 15:05 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    * Read-modify-write a Policy to insert or remove new bindings for the given member and roles.
The docs suggest doing a read-modify-write:
https://cloud.google.com/iam/docs/granting-changing-revoking-access

> Read-Modify-Write: A common pattern for updating a resource's metadata, such as the Policy, is to read its current state, update the data locally, and then send the modified data for writing. This pattern could cause a conflict if two or more independent processes attempt the sequence simultaneously. For example, if two owners for a project try to make conflicting policy changes at the same time, some changes could fail. Cloud IAM solves this problem using an etag property in Cloud IAM policies. This property is used to verify if the policy has changed since the last request. When you make a request to Cloud IAM with an etag value, Cloud IAM compares the etag value in the request with the existing etag value associated with the policy. It writes the policy only if the etag values match.

> When you update a policy, first get the policy using getIamPolicy(), update the policy, and then write the updated policy using setIamPolicy(). Use the etag value when setting the policy only if the corresponding policy in GetPolicyResponse contains an etag value.

Huh, just reading this I wonder if I should be doing something with etags..

2017-10-23 15:27 UTC, dvoet requested changes

2017-10-23 15:27 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +  val id: WorkbenchSubject
id being a WorkbenchSubject is not right. This would mean that it is legal for a person to have an id that is a group name.

2017-10-23 15:27 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
>    def isServiceAccount: Boolean = value.endsWith(".gserviceaccount.com")
I missed this isServiceAccount function go in but don't really like it here. It feels like it should be closer to where we actually care. It feels dirty having googley stuff here.

2017-10-23 15:27 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def addServiceAccountActorRoleForUser(googleProject: String, serviceAccountEmail: WorkbenchUserServiceAccountEmail, userEmail: WorkbenchEmail): Future[Unit]
all of these in here use WorkbenchEmail instead of WorkbenchUserEmail but the parameter name is userEmail. If it must be a user email function signature should be specific.

2017-10-23 15:44 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def addServiceAccountActorRoleForUser(googleProject: String, serviceAccountEmail: WorkbenchUserServiceAccountEmail, userEmail: WorkbenchEmail): Future[Unit]
All of these methods (`addIamRolesForUser` / `removeIamRolesForUser` / `addServiceAccountActorRoleForUser`) can act on users or service accounts. In my case I'm calling them on service accounts (e.g. adding Dataproc Worker role to the pet service account). I can change the parameter name from `userEmail` to `email`.

2017-10-23 15:50 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
>    def isServiceAccount: Boolean = value.endsWith(".gserviceaccount.com")
We care in `HttpGoogleIamDAO` (some calls are slightly different depending whether it's a user or service account) and in Sam when we process the incoming user email header. I could put this function in workbench-libs/google - it feels less dirty there.

2017-10-23 15:55 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +  val id: WorkbenchSubject
Hm, ok. I'll look at this some more. Maybe we need a trait that represents an id that's _not_ a group name.

2017-10-25 23:34 UTC, rtitle commented
@dvoet @helgridly this is ready for re-review, please

2017-10-26 07:13 UTC, helgridly approved these changes
couple of nits but 👍

2017-10-26 07:13 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def createServiceAccount(googleProject: GoogleProject, serviceAccountId: WorkbenchUserServiceAccountId, displayName: WorkbenchUserServiceAccountDisplayName): Future[WorkbenchUserServiceAccount]
changing function signatures = you should rev the module version

2017-10-26 07:13 UTC, helgridly commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +    // Note the project here is the one in which we're adding the IAM roles
for all these functions i think it'd be helpful to rename the `googleProject` variable to say _which_ project we mean... might help remove some confusion if they're instead called `serviceAccountProject`, `iamTargetProject`, etc. (that last one is terribly named because i'm not awake yet)

2017-10-26 07:13 UTC, helgridly commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +case class WorkbenchUserEmail(value: String) extends WorkbenchEmail
function go away = bump version

2017-10-26 13:55 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def createServiceAccount(googleProject: GoogleProject, serviceAccountId: WorkbenchUserServiceAccountId, displayName: WorkbenchUserServiceAccountDisplayName): Future[WorkbenchUserServiceAccount]
yep, will do

2017-10-27 18:20 UTC, merged