GAWB-2811 Added utils to find service accounts
broadinstitute/workbench-libs pull request #35
Opened 2017-10-31 21:26 UTC by helgridly

Supports upcoming Sam PR to not get confused if a service account already exists in Google (e.g. on FiaB).

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2017-10-31 21:44 UTC, helgridly commented
Boo: coverage is dropping because mocks live in `main` when they should live in `test`. We should fix this, but I'm not going to now.

2017-11-01 00:46 UTC, rtitle requested changes

2017-11-01 00:46 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +      serviceAccount.getDisplayName
Unnecessary line

2017-11-01 00:46 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +  override def findServiceAccount(serviceAccountProject: GoogleProject, serviceAccountId: WorkbenchUserServiceAccountId): Future[WorkbenchUserServiceAccount] = {
Should this return `Future[Option[WorkbenchUserServiceAccount]]`? I think as it stands this would be a failed future (404) if the service account is not found.

2017-11-01 00:46 UTC, rtitle commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala
> +      case t: GoogleJsonResponseException if t.getStatusCode == 404 =>
Ah I see - I would slightly prefer `findServiceAccount` to return an Option instead of dealing with the 404 here.

Also should be able to use `retryWithRecoverWhen500orGoogleError` in `findServiceAccount`.

2017-11-01 13:08 UTC, jmthibault79 approved these changes

2017-11-01 15:12 UTC, helgridly commented
@rtitle ready for re-review. i used a monad transformer :)

2017-11-01 16:41 UTC, rtitle approved these changes
Looks good to me!

2017-11-01 16:54 UTC, merged