IA-2369 add publishNativeOne
broadinstitute/workbench-libs pull request #421
Opened 2020-12-07 22:14 UTC by Qi77Qi

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2020-12-07 22:21 UTC, Qi77Qi commented on google2/CHANGELOG.md
> -## 0.18
version wasn't bumped properly in previous PR..hence, just moving this to 0.17...

2020-12-08 14:06 UTC, kyuksel requested changes
Looks good overall. I think it needs rebasing, though.

2020-12-08 14:06 UTC, kyuksel commented on README.md
> -Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google2" % "0.18-626dbbc"`
`develop` is at version `0.18`. May want to rebase.

2020-12-08 14:06 UTC, kyuksel commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +
Could you explain the significance of `Native` in some of these method names?

2020-12-08 14:08 UTC, Qi77Qi commented on google2/src/main/scala/org/broadinstitute/dsde/workbench/google2/GooglePublisherInterpreter.scala
> +
`Native` just meant the function takes a `PubsubMessage` object directly which comes from google's library

2020-12-08 14:09 UTC, Qi77Qi commented on README.md
> -Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google2" % "0.18-626dbbc"`
this was intentional at the time becuz I thought last PR had a mistake not bumping the version. But it seems like it did, so I reverted this change

2020-12-08 14:09 UTC, kyuksel approved these changes
:shipit:

2020-12-08 14:34 UTC, merged