Reorg service account model
broadinstitute/workbench-libs pull request #45
Opened 2017-11-27 16:31 UTC by dvoet

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2017-11-27 18:40 UTC, MatthewBemis approved these changes
really like the changes to the emails

2017-11-27 21:55 UTC, helgridly approved these changes
i approve of this

2017-11-28 15:07 UTC, breilly2 requested changes
Minor change request.

2017-11-28 15:07 UTC, breilly2 commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/GoogleIamDAO.scala
> +  def addServiceAccountUserRoleForUser(serviceAccountProject: GoogleProject, WorkbenchEmail: WorkbenchEmail, email: WorkbenchEmail): Future[Unit]
Here and on lines 90 and 98 and all related scaladoc: property name shouldn't be `WorkbenchEmail`. At first, this was going to be a nit that it's not camelCase but there are actually 2 parameters of type `WorkbenchEmail` now. Implementations use `serviceAccountEmail` and `userEmail`. Whatever parameter names you choose, they should be descriptive and consistent here and in the concrete implementations.

2017-11-28 20:21 UTC, breilly2 approved these changes
👍

2017-11-28 22:03 UTC, rtitle commented on google/CHANGELOG.md
> +- Wpdated for 0.8 version of model
typo

2017-11-28 22:06 UTC, rtitle approved these changes
Looks good. This will break Leo but that's why we have versioning! This looks much cleaner than the way it was before.

2017-11-28 22:49 UTC, merged

2017-11-29 16:15 UTC, jmthibault79 commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
I'm curious why this is not a `ValueObject` - there's a Swat test that would benefit from that

2017-11-29 16:36 UTC, dvoet commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
Not all subjects have a single value

2017-11-29 17:33 UTC, breilly2 commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
So really `ValueObject` should be renamed to `SingleValueObject`. That would also help avoid the conflict with what I generally think of as a "value object".

2017-11-29 17:37 UTC, rtitle commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
In scala “value class” (or object) typically implies a single value: https://docs.scala-lang.org/overviews/core/value-classes.html

2017-11-29 19:22 UTC, breilly2 commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
Ah, okay. Good to know. Thanks! I still wonder if this could have a name that better describes its purpose instead of the mechanism, but at least now I understand what it's referring to.

2017-11-29 21:28 UTC, jmthibault79 commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
I was interpreting this type as "a thing that has a SubjectID" - is that not correct?  (That is what I want: a generic accessor for a user's or service account's Subject ID.

2017-11-29 21:33 UTC, dvoet commented
Those are not the only kind of subjects

On Wed, Nov 29, 2017 at 4:28 PM jmthibault79 <notifications@github.com>
wrote:

> *@jmthibault79* commented on this pull request.
> ------------------------------
>
> In
> model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> <https://github.com/broadinstitute/workbench-libs/pull/45#discussion_r153920093>
> :
>
> >  }
>
> -sealed trait WorkbenchSubject {
> -  def emailOf(emailString: String): WorkbenchEmail = this match {
> -    case _: WorkbenchUserId => WorkbenchUserEmail(emailString)
> -    case _: WorkbenchGroupIdentity => WorkbenchGroupEmail(emailString)
> -    case _: WorkbenchUserServiceAccountSubjectId => WorkbenchUserServiceAccountEmail(emailString)
> -  }
> -}
> -sealed trait WorkbenchEmail extends ValueObject
> +sealed trait WorkbenchSubject
>
> I was interpreting this type as "a thing that has a SubjectID" - is that
> not correct? (That is what I want: a generic accessor for a user's or
> service account's Subject ID.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/workbench-libs/pull/45#discussion_r153920093>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABc2tatyQEMHWMf8LSl6PZOU8ckpCwRXks5s7cyAgaJpZM4Qr6oJ>
> .
>

2017-11-30 15:29 UTC, breilly2 commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/WorkbenchIdentity.scala
> +sealed trait WorkbenchSubject
@dvoet said,

> Those are not the only kind of subjects

Is there an opportunity to clarify this, maybe by choosing a name other than `WorkbenchSubject`? I can understand using "subject" can cause confusion as it did for Joel. Does "subject" refer to something in Google's vocabulary? LDAP's? Something else? I worry that we may be borrowing vocabulary from one context that conflicts with another. We should be clear about which meaning it has in the context of our code.