AS-632: Add enableRequesterPays
broadinstitute/workbench-libs pull request #491
Opened 2021-02-08 17:25 UTC by ansingh7115

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2021-02-10 15:18 UTC, MatthewBemis reviewed
The change looks good. Can you also add the changes to the README and serviceTest CHANGELOG to note what updated and do the `TRAVIS-REPLACE-ME` dance?

2021-02-10 16:01 UTC, davidangb commented
+1 to Matt's comment; the code change itself looks good.

2021-02-10 16:09 UTC, ansingh7115 commented
Whoops! Totally forgot...

2021-02-10 16:19 UTC, MatthewBemis approved these changes

2021-02-10 16:22 UTC, davidangb approved these changes

2021-02-11 16:56 UTC, ansingh7115 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/dao/Google.scala
> +    .getService
this `storageOptions` is the only change in this file, everything else is auto formatting

2021-02-11 17:19 UTC, davidangb requested changes

2021-02-11 17:19 UTC, davidangb commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/dao/Google.scala
> +    .getService
I think this change breaks the encapsulation model between `serviceTest` and `google`. To follow the current pattern, I think you should:
* add a new `setRequesterPays` method to `o.b.d.workbench.google.HttpGoogleStorageDAO`, and undo all changes in `serviceTest`
* import the newer snapshot of `google` in Rawls
* in Rawls' automation `WorkspaceApiSpec`, `import o.b.d.workbench.dao.Google. googleStorageDAO` and simply call `googleStorageDAO.setRequesterPays()`. See `RawlsApiSpec` for example usages.

2021-02-12 19:31 UTC, davidangb commented on project/Dependencies.scala
> +    googleStorageNew
can `googleStorageNew` now be removed from serviceTest dependencies?

2021-02-12 19:31 UTC, davidangb commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  }
I am ok with this approach if it's the only feasible one, but if the client libraries work, I think we should try to use those. Something like this, maybe? This is untested, I don't know if it has drawbacks:
```
    import com.google.api.services.storage.model.{Bucket=>GoogleBucket}

    val rp = new Bucket.Billing().setRequesterPays(true)
    storage.buckets().patch(bucketName, new GoogleBucket().setBilling(rp))
```

2021-02-12 19:31 UTC, davidangb commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  def enableRequesterPays(projectName: String, bucketName: String): Future[Unit] = {
how about making this `setRequesterPays` and accept a Boolean, so we can turn off RP as well?

2021-02-12 19:39 UTC, davidangb commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  }
might also want to wrap this inside a call to `getBucket` - see if the current RP value is already what we want it to be; if it is, skip the patch call entirely

2021-02-12 21:42 UTC, ansingh7115 commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  }
Thank you - I didn't realize you could just use Billing() - I was following https://cloud.google.com/storage/docs/using-requester-pays#code-samples

2021-02-13 00:22 UTC, MatthewBemis approved these changes
👍 pending the README.md fix

2021-02-13 00:22 UTC, MatthewBemis commented on README.md
> +Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-service-test" % "0.18-TRAVIS-REPLACE-ME" % "test" classifier "tests"`
this change should be in the `google` section, right?

2021-02-13 00:27 UTC, ansingh7115 commented on README.md
> +Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-service-test" % "0.18-TRAVIS-REPLACE-ME" % "test" classifier "tests"`
ugh why am i so forgetful

2021-02-13 18:44 UTC, davidangb approved these changes
:+1: code looks good! Thanks for all the iteration on this one.

Last thing: have you - and if not, could you - just try the patch against a real bucket and look at the debug logs to see what's being sent, and ensure it has the right effect on the bucket?

2021-02-16 04:18 UTC, ansingh7115 commented
Bucket Details before enabling:

`{
  "etag": "CAI=",
  "iamConfiguration": {
    "bucketPolicyOnly": {
      "enabled": true,
      "lockedTime": "2021-05-17T04:12:57.013Z"
    },
    "uniformBucketLevelAccess": {
      "enabled": true,
      "lockedTime": "2021-05-17T04:12:57.013Z"
    }
  },
  "id": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "kind": "storage#bucket",
  "labels": {
    "security": "low"
  },
  "location": "US",
  "locationType": "multi-region",
  "logging": {
    "logBucket": "storage-logs-gpalloc-dev-master-yruq8mo",
    "logObjectPrefix": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2"
  },
  "metageneration": "2",
  "name": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "projectNumber": "104034583618",
  "selfLink": "https://www.googleapis.com/storage/v1/b/fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "storageClass": "STANDARD",
  "timeCreated": "2021-02-16T04:12:57.013Z",
  "updated": "2021-02-16T04:12:57.850Z"
}`
Bucket Details after enabling:
`{
  "billing": {
    "requesterPays": true
  },
  "etag": "CAM=",
  "iamConfiguration": {
    "bucketPolicyOnly": {
      "enabled": true,
      "lockedTime": "2021-05-17T04:12:57.013Z"
    },
    "uniformBucketLevelAccess": {
      "enabled": true,
      "lockedTime": "2021-05-17T04:12:57.013Z"
    }
  },
  "id": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "kind": "storage#bucket",
  "labels": {
    "security": "low"
  },
  "location": "US",
  "locationType": "multi-region",
  "logging": {
    "logBucket": "storage-logs-gpalloc-dev-master-yruq8mo",
    "logObjectPrefix": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2"
  },
  "metageneration": "3",
  "name": "fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "projectNumber": "104034583618",
  "selfLink": "https://www.googleapis.com/storage/v1/b/fc-831b1be9-3689-474e-a890-b1594bdaf5f2",
  "storageClass": "STANDARD",
  "timeCreated": "2021-02-16T04:12:57.013Z",
  "updated": "2021-02-16T04:12:59.999Z"
}`

It appears that the details prior to enabling RP don't have `"billing"`

2021-02-16 04:23 UTC, merged