Add TraceId to ErrorReport
broadinstitute/workbench-libs pull request #501
Opened 2021-02-11 18:11 UTC by ehanna4

Add TraceId to ErrorReport so we can show traceid in a more user friendly way on Leo

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2021-02-12 15:46 UTC, Qi77Qi approved these changes
first wb-libs PR! 🎉

2021-02-12 15:54 UTC, Qi77Qi requested changes
https://broadinstitute.slack.com/archives/GB1VAM14J/p1613144892047500?thread_ts=1613071326.027800&cid=GB1VAM14J

2021-02-12 16:20 UTC, Qi77Qi commented on README.md
> -Latest SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-error-reporting" % "0.1-92fcd96"`
need to update this for `model` too :)

2021-02-12 16:36 UTC, Qi77Qi approved these changes
:shipit:

2021-02-12 16:37 UTC, Qi77Qi commented on model/CHANGELOG.md
> +SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-model" % "0.14-TRAVIS-REPLACE-ME"`
oh actually, can you add a comment, something like "add `TraceId` to `ErrorReport`"

2021-02-16 14:01 UTC, kyuksel requested changes
Congratulations on your first workbench-libs PR, Emily 👏🏼 

Left a comment regarding the nature of the change (i.e. breaking) as opposed to what's implied from the change log (i.e. non-breaking).

2021-02-16 14:01 UTC, kyuksel commented on model/src/main/scala/org/broadinstitute/dsde/workbench/model/ErrorReport.scala
> +    ErrorReport(source.source, message, statusCode, causes, stackTrace, exceptionClass, traceId)
Adding a parameter to a class constructor (`def apply()` in this case) with no default value seems like a breaking change to me as existing callers of the constructor won't be able to keep calling it the same way. Am I missing something?

2021-02-16 20:51 UTC, kyuksel approved these changes
:shipit:

2021-02-16 20:58 UTC, merged