2801 sam
broadinstitute/workbench-libs pull request #53
Opened 2017-12-14 20:02 UTC by UrsaStutsman

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2018-01-02 20:08 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Sam.scala
> +    admin.deletePetServiceAccount(userInfo.userSubjectId)(UserPool.chooseAdmin.makeAuthToken())
If an admin auth token is passed in to `removePet` (probably using an implicit parameter list like the other functions) then `Sam` won't need `UserPool` at all. This would be cleaner and would also allow us to separate the work of pulling in `UserPool`.

We should still pull in `UserPool` so don't worry... the time you spent on that was worthwhile!

2018-01-23 20:38 UTC, kyuksel commented
[This PR](https://github.com/broadinstitute/firecloud-ui/pull/1135/files) adds some users for free trial purposes (it's been blocked for SWAT issues for quite some time now). Not sure if there's a process to resolve such conflicts?

2018-01-23 23:05 UTC, kyuksel commented
Does it make sense to move `package org.broadinstitute.dsde.workbench.model.google` to the `google` module?

2018-01-23 23:06 UTC, kyuksel requested changes

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +}
Nit: Add newline

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +object Config extends Config {
Remove `extends Config`

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +trait Config
Remove the above line

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +  }
Nit: two redundant empty lines

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/UserPool.scala
> +}
Nit: add newline

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/UserPool.scala
> +
Nit: remove redundant empty line

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/dao/Google.scala
> +}
Nit: add newline

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodData.scala
> +
Nit: remove redundant empty line

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/MethodFixtures.scala
> +
Nit: remove redundant empty line

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/WorkspaceFixtures.scala
> +
Nit: Consider adding a description for `withClonedWorkspace` (especially since it's a library method)

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/FireCloud.scala
> +
Rename the file name as `FireCloudClient.scala` to match the trait name

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Sam.scala
> +object Sam extends Sam {
Remove `extends Sam`?

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Thurloe.scala
> +object Thurloe extends Thurloe
Remove the above line

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/Awaiter.scala
> +}
Nit: add newline

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/util/ExceptionHandling.scala
> +//trait ExceptionHandling { self: LazyLogging =>
Remove lines 7 through 9

2018-01-23 23:06 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/util/Retry.scala
> +  def retry[T](remainingBackOffIntervals: Seq[FiniteDuration])(op: => Option[T]): Option[T] = {
Add `@annotation.tailrec` so we can get compilation warnings if the method isn't tail recursive.

2018-01-24 13:29 UTC, UrsaStutsman commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +trait Config
trait Config makes it easier to use in other files that import this.

2018-01-24 14:30 UTC, kyuksel approved these changes
👍ed as the initial stage to get things going. Would highly recommend going back and doing a clean-up once everything is migrated and functional.

2018-01-24 15:48 UTC, dvoet commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/CleanUp.scala
> +  private val cleanUpFunctions = mutable.MutableList[() => Any]()
use a thread safe list implementation

2018-01-24 15:49 UTC, dvoet approved these changes

2018-01-24 21:24 UTC, breilly2 approved these changes
👍  Only necessary change is using `ConcurrentLinkedDeque.addFirst` in `CleanUp`. Everything else is a question or can wait until after this is merged.

2018-01-24 21:24 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/config/Config.scala
> +package org.broadinstitute.dsde.workbench.config
I'm still unsure of all of this config ending up in workbench-libs. Some of it might belong, such as chrome settings used by core selenium helpers. Some of it probably doesn't, such as FireCloud base URL.

2018-01-24 21:24 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/CleanUp.scala
> +      cleanUpFunctions.add(f _)
The original code would prepend `f`. Use a `ConcurrentLinkedDeque` so you can use `addFirst` here.

2018-01-24 21:24 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/test/WebBrowserUtil.scala
> +    def spinner(text: String, timeOutInSeconds: Long = defaultTimeOutInSeconds)
This is FC specific. We should move this out of workbench-libs at some point (but not right now... more important to get this merged).

2018-01-24 21:24 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +trait Rawls extends RestClient with LazyLogging {
Looks like it's leonardo that wants this to be an object which is why it can't just be a class. Can this be and object instead of a trait, which would then mean that `object Rawls extends Rawls` below wouldn't be needed?

2018-01-24 21:24 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/FireCloudClient.scala
> +trait FireCloudClient {
Are we just keeping this around for now until other code can migrate to `RestClient`?

2018-01-26 22:33 UTC, merged