GAWB-3018 (part 2): Limit key life using Pub Sub triggers
broadinstitute/workbench-libs pull request #59
Opened 2018-01-25 21:25 UTC by MatthewBemis

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2018-01-25 21:28 UTC, MatthewBemis commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
> +  //When we migrate to the com.google.cloud library, we will be able to re-write this to use their implementation
would also need to deal with migrating to using json credentials instead of pem files. unfortunately this seems like the less messy alternative at the moment.

2018-01-26 20:25 UTC, dvoet commented on google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleStorageDAO.scala
>      val getter = getStorage(getBucketServiceAccountCredential).objects().list(bucketName).setPrefix(objectNamePrefix)
the objects.list api call is paginated, need to make sure we get all the pages or provide a way to get the next page

2018-01-26 20:50 UTC, dvoet requested changes
do the paginated thing

2018-01-30 00:54 UTC, dvoet approved these changes

2018-01-31 16:42 UTC, merged