[CA-1318] Add list roles to IAM Dao
broadinstitute/workbench-libs pull request #728
Opened 2021-08-25 20:17 UTC by s-rubenstein

This should be safe to have no version bump

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2021-08-25 20:21 UTC, ehigham approved these changes

2021-08-26 13:00 UTC, andy7i requested changes
This isn't specific to v2_workspaces right? Could we merge this into the main/develop branch and then merge that into v2_workspaces?

2021-08-26 13:00 UTC, andy7i commented on google/CHANGELOG.md
> +-ME"`
```suggestion
SBT dependency: `"org.broadinstitute.dsde.workbench" %% "workbench-google" % "0.21-TRAVIS-REPLACE-ME"`
```

2021-08-26 13:27 UTC, s-rubenstein commented
That's true. I think I built it off of the v2 workspaces branch, but I can reimplement on top of develop.

2021-08-26 13:27 UTC, closed without merging