[notyet] With clean billing project
broadinstitute/workbench-libs pull request #78
Opened 2018-02-07 23:14 UTC by helgridly

Looking for early review here. Note this implies that the structure of auto-tests will need to change; next on my list is writing some documentation about how.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

After merging, _even if you haven't bumped the version_: 
- [ ] Update `README.md` and the `CHANGELOG.md` for any libs you changed with the new dependency string. The git hash is the same short version you see in GitHub (i.e. seven characters). You can commit these changes straight to develop.

2018-02-08 15:55 UTC, kyuksel requested changes
Looks good in general. A few comments inline.

2018-02-08 15:55 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +  private var suiteStack: mutable.Seq[String] = mutable.Seq.empty[String]
I fear that simultaneous calls to methods that update these `var`s may result in unexpected behaviour that may be difficult to troubleshoot.

2018-02-08 15:55 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    opt foreach { gpAllocedProjects += _._1 }
Consider making this a bit more self-documenting. One way is to create something like

```scala
case class GPAllocProject(name: String, bucket: String)
```

and use it in the output types of `GPAlloc.projects.{request,release}Project()` and in

```scala
def requestGPAllocedProject(testSuite: TestSuite): Option[GPAllocProject] = {
    if( ! suiteStack.contains(testSuite.suiteName) ) {
      throw new WorkbenchException(
        "GPAlloc handler doesn't know who you are. Mix in BeforeAndAfterAll to your Suite and call BillingFixtures.registerGPAllocSuite in beforeAll()")
    }

    val project = GPAlloc.projects.requestProject
    project foreach { gpAllocedProjects += _.name }
    project
  }
```

2018-02-08 15:55 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +  private var bNeverCleanUpAgain = false
`b` stands for boolean? It's a bit confusing to me.

2018-02-08 15:55 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    a single outermost ScalaTest Suite that mixes in BeforeAndAfterAll and calls releaseAllGPAllocedProjects in
What happens if we have a crash before `releaseAllGPAllocedProjects` is called or it completes?

2018-02-08 15:55 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +                        (testCode: (String) => Any)(implicit token: AuthToken): Unit = {
align the constructor argument groups for readability

2018-02-08 16:07 UTC, aednichols commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
[`ParallelTestExecution`](http://doc.scalatest.org/3.0.1/index.html#org.scalatest.ParallelTestExecution):

> ScalaTest's normal approach for running suites of tests in parallel is to run different suites in parallel, but the tests of any one suite sequentially.

Given the above, I am worried about the `var`s on the `BillingFixtures` singleton causing concurrency issues.

Just throwing it out there, but we have been playing with the trait below in a different context.

[`SequentialNestedSuiteExecution`](http://doc.scalatest.org/3.0.1/index.html#org.scalatest.SequentialNestedSuiteExecution):

> Mix in this trait into any suite whose nested suites need to be run sequentially even with the rest of the run is being executed concurrently.

2018-02-08 16:14 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    a single outermost ScalaTest Suite that mixes in BeforeAndAfterAll and calls releaseAllGPAllocedProjects in
this: https://github.com/broadinstitute/gpalloc/issues/8

2018-02-08 16:16 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
Hmm, OK. I can make these vars synchronized / more parallel / something.

What are your thoughts around `SequentialNested`? Doing it at the top-level super-Suite is a good way to make tests take forever, I'd imagine.

2018-02-08 16:48 UTC, aednichols commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
`ParallelTestExecution` is probably more appropriate, shouldn't slow things down (may even speed them up)

> To make it easier for users to write tests that run in parallel, this trait runs each test in its own instance of the class. Running each test in its own instance enables tests to use the same instance vars and mutable objects referenced from instance variables without needing to synchronize.

2018-02-08 16:52 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
> I can make these vars synchronized / more parallel / something.

I have a mini library for lock synchronization from a previous project. If that'd help, let me know.

2018-02-08 16:52 UTC, aednichols commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +  private var bNeverCleanUpAgain = false
Pretty common pattern in dynamically-typed languages, used to see it a lot in PHP

2018-02-08 16:55 UTC, kyuksel commented
What's the testing strategy around this code? Should we create a UI test that goes through the nesting scenarios and also benchmark performance if necessary?

2018-02-08 17:32 UTC, kyuksel commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +  private var bNeverCleanUpAgain = false
I see

2018-02-08 18:14 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
Standard synchronization primitives should work fine here. Will change.

2018-02-08 18:14 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +  private var bNeverCleanUpAgain = false
This is a hangover from my previous life as a C++ developer, where we did hungarian notation for _everything_. I've mostly kicked the habit but b-for-bool sticks with me.

2018-02-08 21:59 UTC, helgridly commented
@kyuksel @aednichols re-review plx

2018-02-08 22:00 UTC, helgridly commented
re testing strategy -- once we get an allocator instance stood up we'll try it out, probably manually, before merging this PR

2018-02-08 23:36 UTC, kyuksel approved these changes
👍ing pending tests

2018-02-12 14:59 UTC, aednichols commented
Can we use this to pre-allocate projects for our actual users, not just Selenium?

Should we do that first?

2018-02-12 16:39 UTC, helgridly commented
Facetalked with Adam, the question was "can we do this in prod" and the answer is "no, it's more complicated in prod / in tests we rely on the fiab db being taken down to clean up the projects / we don't have code to switcharoo the billing account". We could but it's not an immediate prio and certainly not for this service.

2018-02-17 00:53 UTC, helgridly commented on project/Publishing.scala
> +      publishArtifact in Compile := true,
I hoped this would fix the no-downloaded-sources issue, but it didn't.

2018-02-20 15:53 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
I was going to quote the same bit of `ParallelTestExecution` that @aednichols did. My reading of that is that we don't need to do any synchronization ourselves. Do others disagree?

2018-02-20 16:15 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +    "before and after the entire test run" mechanism, we are forced to mandate that all tests are nested inside
These vars are shared by all suites (by design) because they're in a companion object. If they might need synchronization then might as well leave this here.

2018-02-20 19:57 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def claimProject(projectName: String, cromwellAuthBucket: String, newOwner: String)(implicit token: AuthToken): Unit = {
Add a short comment about why releaseProject is elsewhere

2018-02-20 19:59 UTC, jmthibault79 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/RestClient.scala
> +  def extractResponseString(response: HttpResponse): String = {
👍 this stupid thing is all over FireCloudClient too btw

2018-02-20 19:59 UTC, jmthibault79 approved these changes

2018-02-21 01:43 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GPAllocFixtures.scala
> +  private var bNeverCleanUpAgain = false
Not sure if this boolean is going to be accessed in parallel -- probably not since it's only used in `beforeAll`/`afterAll`? Still it might be nice to use `AtomicBoolean` to protect against concurrency issues.

2018-02-21 01:45 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GPAllocFixtures.scala
> +    opt foreach { p => gpAllocedProjects.put(p.projectName, authToken) }
So we're storing the auth token in the `ConcurrentHashMap` - what if the token expires before the tests finish? Does releasing the projects fail or is there something to handle that?

2018-02-21 02:00 UTC, rtitle commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/RestClient.scala
> +  def extractResponseString(response: HttpResponse): String = {
Yikes. A better way might be:
```
    val responseStringFuture: Future[String] = response.entity.toStrict(5 minutes).map(_.data.utf8String)
    Await.result(responseStringFuture, 5.minute)
```
Also not a fan of sprinkling `Await.result`s in this code but I'll choose my battles.

2018-02-21 02:04 UTC, rtitle approved these changes
Looks good. The stuff handling suite set up/tear down is a _little_ hairy, but it makes sense and does seem to be the ScalaTest-recommended way of doing this.

2018-02-21 02:24 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GPAllocFixtures.scala
> +    opt foreach { p => gpAllocedProjects.put(p.projectName, authToken) }
Releasing the project will fail (but then the allocator will auto-clear it up in two hours anyway). Consider this a nudge to have your tests not take an hour ;)

2018-02-21 02:59 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/Rawls.scala
> +    def claimProject(projectName: String, cromwellAuthBucket: String, newOwner: String)(implicit token: AuthToken): Unit = {
done

2018-02-21 02:59 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/service/RestClient.scala
> +  def extractResponseString(response: HttpResponse): String = {
done

2018-02-21 03:00 UTC, helgridly commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GPAllocFixtures.scala
> +  private var bNeverCleanUpAgain = false
agree it's probably unnecessary, but i did it anyway

2018-02-21 14:36 UTC, breilly2 commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/GPAllocFixtures.scala
> +  private var bNeverCleanUpAgain = false
Nit: Just be careful of unnecessary thread safety affecting readability. In this case, someone reading `AtomicBoolean` could reasonably assume that it was determined to be necessary, possibly communicating an incorrect model of the instance's thread context.

2018-02-21 16:17 UTC, merged