[CA-1103] Remove v1 billing project creation from workbench-libs
broadinstitute/workbench-libs pull request #943
Opened 2022-03-31 20:13 UTC by ehigham

RR: https://broadworkbench.atlassian.net/browse/CA-1103
Creating temporary v1 billing projects via GPAlloc has been a source of
sporadic failures in swatomation tests across terra core services.
Since project-per-workspace was launched, v1 billing projects have been
deprecated in favour of newer, shinier v2 billing projects and CI have
sought to purge GPAlloc from our testing infrastructure.
In this change, I have removed all mention of GPAlloc and v1 billing
projects from workbenchLibs/workbenchServiceTest. I've replaced the
BillingFixtures trait with an object that facilitates creation, use and
clean-up of temporary v2 billing projects. Why an object and not a
trait? Because inheritance is the root-cause of evil in this world. It
is safe to say that Vladimir Putin would not be where he is today if
it were not for inheritance. Thus, it is our moral obligation to
remove it from the world.

**PR checklist**
- [ ] For each library you've modified here, decide whether it requires a major, minor, or no version bump. (Click [here](/broadinstitute/workbench-libs/blob/develop/CONTRIBUTING.md) for guidance)

If you're doing a **major** or **minor** version bump to any libraries:
- [ ] Bump the version in `project/Settings.scala` `createVersion()`
- [ ] Update `CHANGELOG.md` for those libraries
- [ ] I promise I used `@deprecated` instead of deleting code where possible

In all cases:
- [ ] Replace the appropriate version hashes in `README.md` and the `CHANGELOG.md` for any libs you changed with `TRAVIS-REPLACE-ME` to auto-update the version string
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green (CI _and_ coverage tests)
- [ ] Squash commits and **merge to develop**
- [ ] Delete branch after merge

2022-04-05 15:03 UTC, andy7i commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +                                    prefix: Option[String] = None,
I like the idea of being explicit up front and using a default parameter value, but it's not a strong preference.
```suggestion
                                    prefix: String = "tmp-",
```

2022-04-05 15:03 UTC, andy7i commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +        .++(UUID.randomUUID.toString.replace("-", ""))
Not entirely sure how worried we should be, but I'm mildly concerned about how the length of the UUIDs will be 10 characters long if the default prefix is 20 characters. (I guess I'm mostly concerned due to being burned by flaky tests and the risk of collisions if the UUID part is too short).

2022-04-05 15:03 UTC, andy7i commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +        .++(UUID.randomUUID.toString.replace("-", ""))
I looked into this a bit more and UUID.randomUUID generates a random string (aka a version 4 uuid), which is not prefixed with a timestamp. Also, a 10 character UUID gives us ~1 trillion IDs. In conclusion, I think we're good..

2022-04-05 15:03 UTC, andy7i commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +   * @param billingAccountName Name of Google billing account the new billing project will bill to.
the API takes in a billing account ID (like `"billingAccount":"billingAccounts/00708C-45D19D-27AAFA"`) so I think we should rename this to billingAccount or billingAccountId or something like that

2022-04-05 17:06 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +                                    prefix: Option[String] = None,
I spent a long time thinking about this and I went with `Option` because:
1. In the signature it tells me which parameters are optional
3. it allows me to know if a user has specified preference or not and compute defaults from other arguments. 

Consider the following example. Let's say I want to default the clone billing project to the source billing project and compute a prefix for the clone based upon the name of the source workspace. I cannot do this using default parameter values because default parameter values cannot be dependent on actual parameter values.
```scala
def temporaryWorkspaceClone(
  sourceBillingProject: String,
  sourceWorkspaceName: String.
  cloneBillingProject: String = sourceBillingProject,
  cloneWorkpacePrefix: String = sourceWorkspaceName + "-clone-",
   ...
```
For this reason, using `Option` provides a consistent interface for documenting and handling default parameters.

2022-04-05 17:08 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +        .++(UUID.randomUUID.toString.replace("-", ""))
We're very very unlikely to get a UUID collision. Do we have a limit on the length of a v2 billing project name?

2022-04-05 17:08 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +   * @param billingAccountName Name of Google billing account the new billing project will bill to.
sure.

2022-04-05 17:38 UTC, gpolumbo-broad commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +                                    prefix: Option[String] = None,
love this discussion!  If we ever wanted to start creating a team style guide, this is the sort of thing I would put there.

2022-04-05 17:55 UTC, gpolumbo-broad requested changes

2022-04-05 17:55 UTC, gpolumbo-broad commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      billingProject <- Resource.make(createBillingProject)(destroyBillingProject)
In order to delete a Billing Project, it must no longer have any Workspaces within it.  We can maybe count on users cleaning up their own Workspaces or using a "withTemporaryWorkspace" context in their test.  Or we can just force that cleanup to happen here, before destroying the Billing Project or as part of the `destroyBillingProject` method, we first delete all Workspaces within it.

2022-04-05 18:50 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      billingProject <- Resource.make(createBillingProject)(destroyBillingProject)
I actually prefer not to as this has helped identify issues in the tests with permissions that helped me fix them.

2022-04-05 18:51 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +      billingProject <- Resource.make(createBillingProject)(destroyBillingProject)
It's not just workspaces too - it's groups. There could be anything. I don't think we should enumerate and clean all them up here.

2022-04-06 15:53 UTC, andy7i commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +        .++(UUID.randomUUID.toString.replace("-", ""))
looks like we still limit it to 30 chars, though I don't think that's necessary anymore
https://github.com/broadinstitute/rawls/blob/develop/model/src/main/scala/org/broadinstitute/dsde/rawls/StringValidationUtils.scala#L44

2022-04-06 15:54 UTC, andy7i approved these changes
LGTM!

2022-04-06 16:16 UTC, ehigham commented on serviceTest/src/test/scala/org/broadinstitute/dsde/workbench/fixture/BillingFixtures.scala
> +        .++(UUID.randomUUID.toString.replace("-", ""))
Thanks. I guess that's a hangover from v1. Yeah we probably should increase this.

2022-04-07 13:50 UTC, gpolumbo-broad approved these changes

2022-04-07 16:07 UTC, merged